/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JayeshScrapWithdrawRequest model module.
 * @module model/JayeshScrapWithdrawRequest
 * @version 1.0.0
 */
class JayeshScrapWithdrawRequest {
    /**
     * Constructs a new <code>JayeshScrapWithdrawRequest</code>.
     * @alias module:model/JayeshScrapWithdrawRequest
     * @param withdrawAmount {Number} Amount withdrawn for this transaction
     * @param withdrawDate {Date} Date of this withdrawal transaction
     */
    constructor(withdrawAmount, withdrawDate) { 
        
        JayeshScrapWithdrawRequest.initialize(this, withdrawAmount, withdrawDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, withdrawAmount, withdrawDate) { 
        obj['withdrawAmount'] = withdrawAmount;
        obj['withdrawDate'] = withdrawDate;
    }

    /**
     * Constructs a <code>JayeshScrapWithdrawRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JayeshScrapWithdrawRequest} obj Optional instance to populate.
     * @return {module:model/JayeshScrapWithdrawRequest} The populated <code>JayeshScrapWithdrawRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JayeshScrapWithdrawRequest();

            if (data.hasOwnProperty('withdrawAmount')) {
                obj['withdrawAmount'] = ApiClient.convertToType(data['withdrawAmount'], 'Number');
            }
            if (data.hasOwnProperty('withdrawDate')) {
                obj['withdrawDate'] = ApiClient.convertToType(data['withdrawDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JayeshScrapWithdrawRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JayeshScrapWithdrawRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JayeshScrapWithdrawRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

JayeshScrapWithdrawRequest.RequiredProperties = ["withdrawAmount", "withdrawDate"];

/**
 * Amount withdrawn for this transaction
 * @member {Number} withdrawAmount
 */
JayeshScrapWithdrawRequest.prototype['withdrawAmount'] = undefined;

/**
 * Date of this withdrawal transaction
 * @member {Date} withdrawDate
 */
JayeshScrapWithdrawRequest.prototype['withdrawDate'] = undefined;






export default JayeshScrapWithdrawRequest;

