/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ElementType from './ElementType';
import JayeshScrapContractor from './JayeshScrapContractor';
import JayeshScrapWithdrawal from './JayeshScrapWithdrawal';

/**
 * The JayeshScrap model module.
 * @module model/JayeshScrap
 * @version 1.0.0
 */
class JayeshScrap {
    /**
     * Constructs a new <code>JayeshScrap</code>.
     * @alias module:model/JayeshScrap
     */
    constructor() { 
        
        JayeshScrap.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JayeshScrap</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JayeshScrap} obj Optional instance to populate.
     * @return {module:model/JayeshScrap} The populated <code>JayeshScrap</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JayeshScrap();

            if (data.hasOwnProperty('scrapId')) {
                obj['scrapId'] = ApiClient.convertToType(data['scrapId'], 'Number');
            }
            if (data.hasOwnProperty('contractor')) {
                obj['contractor'] = JayeshScrapContractor.constructFromObject(data['contractor']);
            }
            if (data.hasOwnProperty('challanNo')) {
                obj['challanNo'] = ApiClient.convertToType(data['challanNo'], 'String');
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], 'String');
            }
            if (data.hasOwnProperty('elementValue')) {
                obj['elementValue'] = ApiClient.convertToType(data['elementValue'], 'Number');
            }
            if (data.hasOwnProperty('elementType')) {
                obj['elementType'] = ElementType.constructFromObject(data['elementType']);
            }
            if (data.hasOwnProperty('totalWeight')) {
                obj['totalWeight'] = ApiClient.convertToType(data['totalWeight'], 'Number');
            }
            if (data.hasOwnProperty('outWeight')) {
                obj['outWeight'] = ApiClient.convertToType(data['outWeight'], 'Number');
            }
            if (data.hasOwnProperty('netWeight')) {
                obj['netWeight'] = ApiClient.convertToType(data['netWeight'], 'Number');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
            if (data.hasOwnProperty('withdrawals')) {
                obj['withdrawals'] = ApiClient.convertToType(data['withdrawals'], [JayeshScrapWithdrawal]);
            }
            if (data.hasOwnProperty('pendingAmount')) {
                obj['pendingAmount'] = ApiClient.convertToType(data['pendingAmount'], 'Number');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('lastUpdatedAt')) {
                obj['lastUpdatedAt'] = ApiClient.convertToType(data['lastUpdatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JayeshScrap</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JayeshScrap</code>.
     */
    static validateJSON(data) {
        // validate the optional field `contractor`
        if (data['contractor']) { // data not null
          JayeshScrapContractor.validateJSON(data['contractor']);
        }
        // ensure the json data is a string
        if (data['challanNo'] && !(typeof data['challanNo'] === 'string' || data['challanNo'] instanceof String)) {
            throw new Error("Expected the field `challanNo` to be a primitive type in the JSON string but got " + data['challanNo']);
        }
        // ensure the json data is a string
        if (data['item'] && !(typeof data['item'] === 'string' || data['item'] instanceof String)) {
            throw new Error("Expected the field `item` to be a primitive type in the JSON string but got " + data['item']);
        }
        if (data['withdrawals']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['withdrawals'])) {
                throw new Error("Expected the field `withdrawals` to be an array in the JSON data but got " + data['withdrawals']);
            }
            // validate the optional field `withdrawals` (array)
            for (const item of data['withdrawals']) {
                JayeshScrapWithdrawal.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} scrapId
 */
JayeshScrap.prototype['scrapId'] = undefined;

/**
 * @member {module:model/JayeshScrapContractor} contractor
 */
JayeshScrap.prototype['contractor'] = undefined;

/**
 * @member {String} challanNo
 */
JayeshScrap.prototype['challanNo'] = undefined;

/**
 * @member {Date} orderDate
 */
JayeshScrap.prototype['orderDate'] = undefined;

/**
 * @member {String} item
 */
JayeshScrap.prototype['item'] = undefined;

/**
 * @member {Number} elementValue
 */
JayeshScrap.prototype['elementValue'] = undefined;

/**
 * @member {module:model/ElementType} elementType
 */
JayeshScrap.prototype['elementType'] = undefined;

/**
 * @member {Number} totalWeight
 */
JayeshScrap.prototype['totalWeight'] = undefined;

/**
 * @member {Number} outWeight
 */
JayeshScrap.prototype['outWeight'] = undefined;

/**
 * @member {Number} netWeight
 */
JayeshScrap.prototype['netWeight'] = undefined;

/**
 * @member {Number} rate
 */
JayeshScrap.prototype['rate'] = undefined;

/**
 * Calculated as netWeight * rate
 * @member {Number} totalAmount
 */
JayeshScrap.prototype['totalAmount'] = undefined;

/**
 * List of all withdrawal transactions
 * @member {Array.<module:model/JayeshScrapWithdrawal>} withdrawals
 */
JayeshScrap.prototype['withdrawals'] = undefined;

/**
 * Calculated as totalAmount - sum of all withdrawals
 * @member {Number} pendingAmount
 */
JayeshScrap.prototype['pendingAmount'] = undefined;

/**
 * @member {Date} createdAt
 */
JayeshScrap.prototype['createdAt'] = undefined;

/**
 * @member {Date} lastUpdatedAt
 */
JayeshScrap.prototype['lastUpdatedAt'] = undefined;






export default JayeshScrap;

