/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ElementType from './ElementType';

/**
 * The KevinScrapRequest model module.
 * @module model/KevinScrapRequest
 * @version 1.0.0
 */
class KevinScrapRequest {
    /**
     * Constructs a new <code>KevinScrapRequest</code>.
     * @alias module:model/KevinScrapRequest
     * @param scrapContractorId {Number} ID of the Kevin scrap contractor
     * @param challanNo {String} Challan number
     * @param orderDate {Date} 
     * @param item {String} Item name
     * @param elementValue {Number} Element value
     * @param elementType {module:model/ElementType} 
     * @param totalWeight {Number} Total weight
     * @param outWeight {Number} Out weight
     * @param netWeight {Number} Net weight
     */
    constructor(scrapContractorId, challanNo, orderDate, item, elementValue, elementType, totalWeight, outWeight, netWeight) { 
        
        KevinScrapRequest.initialize(this, scrapContractorId, challanNo, orderDate, item, elementValue, elementType, totalWeight, outWeight, netWeight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, scrapContractorId, challanNo, orderDate, item, elementValue, elementType, totalWeight, outWeight, netWeight) { 
        obj['scrapContractorId'] = scrapContractorId;
        obj['challanNo'] = challanNo;
        obj['orderDate'] = orderDate;
        obj['item'] = item;
        obj['elementValue'] = elementValue;
        obj['elementType'] = elementType;
        obj['totalWeight'] = totalWeight;
        obj['outWeight'] = outWeight;
        obj['netWeight'] = netWeight;
    }

    /**
     * Constructs a <code>KevinScrapRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KevinScrapRequest} obj Optional instance to populate.
     * @return {module:model/KevinScrapRequest} The populated <code>KevinScrapRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KevinScrapRequest();

            if (data.hasOwnProperty('scrapContractorId')) {
                obj['scrapContractorId'] = ApiClient.convertToType(data['scrapContractorId'], 'Number');
            }
            if (data.hasOwnProperty('challanNo')) {
                obj['challanNo'] = ApiClient.convertToType(data['challanNo'], 'String');
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = ApiClient.convertToType(data['item'], 'String');
            }
            if (data.hasOwnProperty('elementValue')) {
                obj['elementValue'] = ApiClient.convertToType(data['elementValue'], 'Number');
            }
            if (data.hasOwnProperty('elementType')) {
                obj['elementType'] = ElementType.constructFromObject(data['elementType']);
            }
            if (data.hasOwnProperty('totalWeight')) {
                obj['totalWeight'] = ApiClient.convertToType(data['totalWeight'], 'Number');
            }
            if (data.hasOwnProperty('outWeight')) {
                obj['outWeight'] = ApiClient.convertToType(data['outWeight'], 'Number');
            }
            if (data.hasOwnProperty('netWeight')) {
                obj['netWeight'] = ApiClient.convertToType(data['netWeight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>KevinScrapRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>KevinScrapRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of KevinScrapRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['challanNo'] && !(typeof data['challanNo'] === 'string' || data['challanNo'] instanceof String)) {
            throw new Error("Expected the field `challanNo` to be a primitive type in the JSON string but got " + data['challanNo']);
        }
        // ensure the json data is a string
        if (data['item'] && !(typeof data['item'] === 'string' || data['item'] instanceof String)) {
            throw new Error("Expected the field `item` to be a primitive type in the JSON string but got " + data['item']);
        }

        return true;
    }


}

KevinScrapRequest.RequiredProperties = ["scrapContractorId", "challanNo", "orderDate", "item", "elementValue", "elementType", "totalWeight", "outWeight", "netWeight"];

/**
 * ID of the Kevin scrap contractor
 * @member {Number} scrapContractorId
 */
KevinScrapRequest.prototype['scrapContractorId'] = undefined;

/**
 * Challan number
 * @member {String} challanNo
 */
KevinScrapRequest.prototype['challanNo'] = undefined;

/**
 * @member {Date} orderDate
 */
KevinScrapRequest.prototype['orderDate'] = undefined;

/**
 * Item name
 * @member {String} item
 */
KevinScrapRequest.prototype['item'] = undefined;

/**
 * Element value
 * @member {Number} elementValue
 */
KevinScrapRequest.prototype['elementValue'] = undefined;

/**
 * @member {module:model/ElementType} elementType
 */
KevinScrapRequest.prototype['elementType'] = undefined;

/**
 * Total weight
 * @member {Number} totalWeight
 */
KevinScrapRequest.prototype['totalWeight'] = undefined;

/**
 * Out weight
 * @member {Number} outWeight
 */
KevinScrapRequest.prototype['outWeight'] = undefined;

/**
 * Net weight
 * @member {Number} netWeight
 */
KevinScrapRequest.prototype['netWeight'] = undefined;






export default KevinScrapRequest;

