/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CashflowParty from './CashflowParty';
import CashflowPaymentType from './CashflowPaymentType';

/**
 * The CashflowEntryResponse model module.
 * @module model/CashflowEntryResponse
 * @version 1.0.0
 */
class CashflowEntryResponse {
    /**
     * Constructs a new <code>CashflowEntryResponse</code>.
     * @alias module:model/CashflowEntryResponse
     */
    constructor() { 
        
        CashflowEntryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CashflowEntryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashflowEntryResponse} obj Optional instance to populate.
     * @return {module:model/CashflowEntryResponse} The populated <code>CashflowEntryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashflowEntryResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('party')) {
                obj['party'] = CashflowParty.constructFromObject(data['party']);
            }
            if (data.hasOwnProperty('paymentType')) {
                obj['paymentType'] = CashflowPaymentType.constructFromObject(data['paymentType']);
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('carryForward')) {
                obj['carryForward'] = ApiClient.convertToType(data['carryForward'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CashflowEntryResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CashflowEntryResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `party`
        if (data['party']) { // data not null
          CashflowParty.validateJSON(data['party']);
        }
        // validate the optional field `paymentType`
        if (data['paymentType']) { // data not null
          CashflowPaymentType.validateJSON(data['paymentType']);
        }
        // ensure the json data is a string
        if (data['note'] && !(typeof data['note'] === 'string' || data['note'] instanceof String)) {
            throw new Error("Expected the field `note` to be a primitive type in the JSON string but got " + data['note']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
CashflowEntryResponse.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
CashflowEntryResponse.prototype['date'] = undefined;

/**
 * @member {Number} amount
 */
CashflowEntryResponse.prototype['amount'] = undefined;

/**
 * @member {module:model/CashflowParty} party
 */
CashflowEntryResponse.prototype['party'] = undefined;

/**
 * @member {module:model/CashflowPaymentType} paymentType
 */
CashflowEntryResponse.prototype['paymentType'] = undefined;

/**
 * @member {String} note
 */
CashflowEntryResponse.prototype['note'] = undefined;

/**
 * True if this entry was auto-created as a carry-forward from previous day
 * @member {Boolean} carryForward
 */
CashflowEntryResponse.prototype['carryForward'] = undefined;






export default CashflowEntryResponse;

