/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CashflowPartySummary model module.
 * @module model/CashflowPartySummary
 * @version 1.0.0
 */
class CashflowPartySummary {
    /**
     * Constructs a new <code>CashflowPartySummary</code>.
     * @alias module:model/CashflowPartySummary
     */
    constructor() { 
        
        CashflowPartySummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CashflowPartySummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashflowPartySummary} obj Optional instance to populate.
     * @return {module:model/CashflowPartySummary} The populated <code>CashflowPartySummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashflowPartySummary();

            if (data.hasOwnProperty('partyId')) {
                obj['partyId'] = ApiClient.convertToType(data['partyId'], 'Number');
            }
            if (data.hasOwnProperty('partyName')) {
                obj['partyName'] = ApiClient.convertToType(data['partyName'], 'String');
            }
            if (data.hasOwnProperty('totalIncome')) {
                obj['totalIncome'] = ApiClient.convertToType(data['totalIncome'], 'Number');
            }
            if (data.hasOwnProperty('totalExpense')) {
                obj['totalExpense'] = ApiClient.convertToType(data['totalExpense'], 'Number');
            }
            if (data.hasOwnProperty('netBalance')) {
                obj['netBalance'] = ApiClient.convertToType(data['netBalance'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CashflowPartySummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CashflowPartySummary</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['partyName'] && !(typeof data['partyName'] === 'string' || data['partyName'] instanceof String)) {
            throw new Error("Expected the field `partyName` to be a primitive type in the JSON string but got " + data['partyName']);
        }

        return true;
    }


}



/**
 * @member {Number} partyId
 */
CashflowPartySummary.prototype['partyId'] = undefined;

/**
 * @member {String} partyName
 */
CashflowPartySummary.prototype['partyName'] = undefined;

/**
 * @member {Number} totalIncome
 */
CashflowPartySummary.prototype['totalIncome'] = undefined;

/**
 * @member {Number} totalExpense
 */
CashflowPartySummary.prototype['totalExpense'] = undefined;

/**
 * @member {Number} netBalance
 */
CashflowPartySummary.prototype['netBalance'] = undefined;






export default CashflowPartySummary;

