/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CashflowEntryRequest model module.
 * @module model/CashflowEntryRequest
 * @version 1.0.0
 */
class CashflowEntryRequest {
    /**
     * Constructs a new <code>CashflowEntryRequest</code>.
     * @alias module:model/CashflowEntryRequest
     * @param date {Date} Entry date (yyyy-MM-dd)
     * @param amount {Number} 
     */
    constructor(date, amount) { 
        
        CashflowEntryRequest.initialize(this, date, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, amount) { 
        obj['date'] = date;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>CashflowEntryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashflowEntryRequest} obj Optional instance to populate.
     * @return {module:model/CashflowEntryRequest} The populated <code>CashflowEntryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashflowEntryRequest();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('partyId')) {
                obj['partyId'] = ApiClient.convertToType(data['partyId'], 'Number');
            }
            if (data.hasOwnProperty('paymentTypeId')) {
                obj['paymentTypeId'] = ApiClient.convertToType(data['paymentTypeId'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CashflowEntryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CashflowEntryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CashflowEntryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['note'] && !(typeof data['note'] === 'string' || data['note'] instanceof String)) {
            throw new Error("Expected the field `note` to be a primitive type in the JSON string but got " + data['note']);
        }

        return true;
    }


}

CashflowEntryRequest.RequiredProperties = ["date", "amount"];

/**
 * Entry date (yyyy-MM-dd)
 * @member {Date} date
 */
CashflowEntryRequest.prototype['date'] = undefined;

/**
 * @member {Number} amount
 */
CashflowEntryRequest.prototype['amount'] = undefined;

/**
 * Optional party reference
 * @member {Number} partyId
 */
CashflowEntryRequest.prototype['partyId'] = undefined;

/**
 * Optional payment type reference
 * @member {Number} paymentTypeId
 */
CashflowEntryRequest.prototype['paymentTypeId'] = undefined;

/**
 * Optional note or description
 * @member {String} note
 */
CashflowEntryRequest.prototype['note'] = undefined;






export default CashflowEntryRequest;

