/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CashflowPaymentTypeSummary model module.
 * @module model/CashflowPaymentTypeSummary
 * @version 1.0.0
 */
class CashflowPaymentTypeSummary {
    /**
     * Constructs a new <code>CashflowPaymentTypeSummary</code>.
     * @alias module:model/CashflowPaymentTypeSummary
     */
    constructor() { 
        
        CashflowPaymentTypeSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CashflowPaymentTypeSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CashflowPaymentTypeSummary} obj Optional instance to populate.
     * @return {module:model/CashflowPaymentTypeSummary} The populated <code>CashflowPaymentTypeSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CashflowPaymentTypeSummary();

            if (data.hasOwnProperty('paymentTypeId')) {
                obj['paymentTypeId'] = ApiClient.convertToType(data['paymentTypeId'], 'Number');
            }
            if (data.hasOwnProperty('paymentTypeName')) {
                obj['paymentTypeName'] = ApiClient.convertToType(data['paymentTypeName'], 'String');
            }
            if (data.hasOwnProperty('totalIncome')) {
                obj['totalIncome'] = ApiClient.convertToType(data['totalIncome'], 'Number');
            }
            if (data.hasOwnProperty('totalExpense')) {
                obj['totalExpense'] = ApiClient.convertToType(data['totalExpense'], 'Number');
            }
            if (data.hasOwnProperty('netBalance')) {
                obj['netBalance'] = ApiClient.convertToType(data['netBalance'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CashflowPaymentTypeSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CashflowPaymentTypeSummary</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['paymentTypeName'] && !(typeof data['paymentTypeName'] === 'string' || data['paymentTypeName'] instanceof String)) {
            throw new Error("Expected the field `paymentTypeName` to be a primitive type in the JSON string but got " + data['paymentTypeName']);
        }

        return true;
    }


}



/**
 * @member {Number} paymentTypeId
 */
CashflowPaymentTypeSummary.prototype['paymentTypeId'] = undefined;

/**
 * @member {String} paymentTypeName
 */
CashflowPaymentTypeSummary.prototype['paymentTypeName'] = undefined;

/**
 * @member {Number} totalIncome
 */
CashflowPaymentTypeSummary.prototype['totalIncome'] = undefined;

/**
 * @member {Number} totalExpense
 */
CashflowPaymentTypeSummary.prototype['totalExpense'] = undefined;

/**
 * @member {Number} netBalance
 */
CashflowPaymentTypeSummary.prototype['netBalance'] = undefined;






export default CashflowPaymentTypeSummary;

