/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CloseDayResponse model module.
 * @module model/CloseDayResponse
 * @version 1.0.0
 */
class CloseDayResponse {
    /**
     * Constructs a new <code>CloseDayResponse</code>.
     * @alias module:model/CloseDayResponse
     */
    constructor() { 
        
        CloseDayResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CloseDayResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CloseDayResponse} obj Optional instance to populate.
     * @return {module:model/CloseDayResponse} The populated <code>CloseDayResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CloseDayResponse();

            if (data.hasOwnProperty('closedDate')) {
                obj['closedDate'] = ApiClient.convertToType(data['closedDate'], 'Date');
            }
            if (data.hasOwnProperty('nextDate')) {
                obj['nextDate'] = ApiClient.convertToType(data['nextDate'], 'Date');
            }
            if (data.hasOwnProperty('totalIncome')) {
                obj['totalIncome'] = ApiClient.convertToType(data['totalIncome'], 'Number');
            }
            if (data.hasOwnProperty('totalExpense')) {
                obj['totalExpense'] = ApiClient.convertToType(data['totalExpense'], 'Number');
            }
            if (data.hasOwnProperty('netBalance')) {
                obj['netBalance'] = ApiClient.convertToType(data['netBalance'], 'Number');
            }
            if (data.hasOwnProperty('carryForwardAmount')) {
                obj['carryForwardAmount'] = ApiClient.convertToType(data['carryForwardAmount'], 'Number');
            }
            if (data.hasOwnProperty('carryForwardType')) {
                obj['carryForwardType'] = ApiClient.convertToType(data['carryForwardType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CloseDayResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CloseDayResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['carryForwardType'] && !(typeof data['carryForwardType'] === 'string' || data['carryForwardType'] instanceof String)) {
            throw new Error("Expected the field `carryForwardType` to be a primitive type in the JSON string but got " + data['carryForwardType']);
        }

        return true;
    }


}



/**
 * @member {Date} closedDate
 */
CloseDayResponse.prototype['closedDate'] = undefined;

/**
 * @member {Date} nextDate
 */
CloseDayResponse.prototype['nextDate'] = undefined;

/**
 * @member {Number} totalIncome
 */
CloseDayResponse.prototype['totalIncome'] = undefined;

/**
 * @member {Number} totalExpense
 */
CloseDayResponse.prototype['totalExpense'] = undefined;

/**
 * @member {Number} netBalance
 */
CloseDayResponse.prototype['netBalance'] = undefined;

/**
 * @member {Number} carryForwardAmount
 */
CloseDayResponse.prototype['carryForwardAmount'] = undefined;

/**
 * INCOME, EXPENSE, or null (when balance is zero)
 * @member {String} carryForwardType
 */
CloseDayResponse.prototype['carryForwardType'] = undefined;






export default CloseDayResponse;

