/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CashflowEntryResponse from './CashflowEntryResponse';

/**
 * The DailySummaryResponse model module.
 * @module model/DailySummaryResponse
 * @version 1.0.0
 */
class DailySummaryResponse {
    /**
     * Constructs a new <code>DailySummaryResponse</code>.
     * @alias module:model/DailySummaryResponse
     */
    constructor() { 
        
        DailySummaryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DailySummaryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DailySummaryResponse} obj Optional instance to populate.
     * @return {module:model/DailySummaryResponse} The populated <code>DailySummaryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DailySummaryResponse();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('totalIncome')) {
                obj['totalIncome'] = ApiClient.convertToType(data['totalIncome'], 'Number');
            }
            if (data.hasOwnProperty('totalExpense')) {
                obj['totalExpense'] = ApiClient.convertToType(data['totalExpense'], 'Number');
            }
            if (data.hasOwnProperty('netBalance')) {
                obj['netBalance'] = ApiClient.convertToType(data['netBalance'], 'Number');
            }
            if (data.hasOwnProperty('dayClosed')) {
                obj['dayClosed'] = ApiClient.convertToType(data['dayClosed'], 'Boolean');
            }
            if (data.hasOwnProperty('carryForwardAmount')) {
                obj['carryForwardAmount'] = ApiClient.convertToType(data['carryForwardAmount'], 'Number');
            }
            if (data.hasOwnProperty('carryForwardType')) {
                obj['carryForwardType'] = ApiClient.convertToType(data['carryForwardType'], 'String');
            }
            if (data.hasOwnProperty('incomes')) {
                obj['incomes'] = ApiClient.convertToType(data['incomes'], [CashflowEntryResponse]);
            }
            if (data.hasOwnProperty('expenses')) {
                obj['expenses'] = ApiClient.convertToType(data['expenses'], [CashflowEntryResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DailySummaryResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DailySummaryResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['carryForwardType'] && !(typeof data['carryForwardType'] === 'string' || data['carryForwardType'] instanceof String)) {
            throw new Error("Expected the field `carryForwardType` to be a primitive type in the JSON string but got " + data['carryForwardType']);
        }
        if (data['incomes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['incomes'])) {
                throw new Error("Expected the field `incomes` to be an array in the JSON data but got " + data['incomes']);
            }
            // validate the optional field `incomes` (array)
            for (const item of data['incomes']) {
                CashflowEntryResponse.validateJSON(item);
            };
        }
        if (data['expenses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['expenses'])) {
                throw new Error("Expected the field `expenses` to be an array in the JSON data but got " + data['expenses']);
            }
            // validate the optional field `expenses` (array)
            for (const item of data['expenses']) {
                CashflowEntryResponse.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Date} date
 */
DailySummaryResponse.prototype['date'] = undefined;

/**
 * @member {Number} totalIncome
 */
DailySummaryResponse.prototype['totalIncome'] = undefined;

/**
 * @member {Number} totalExpense
 */
DailySummaryResponse.prototype['totalExpense'] = undefined;

/**
 * Positive means income surplus, negative means expense surplus
 * @member {Number} netBalance
 */
DailySummaryResponse.prototype['netBalance'] = undefined;

/**
 * Whether close-day has been called for this date
 * @member {Boolean} dayClosed
 */
DailySummaryResponse.prototype['dayClosed'] = undefined;

/**
 * Amount that will/was carried to next day. Null if balance is zero.
 * @member {Number} carryForwardAmount
 */
DailySummaryResponse.prototype['carryForwardAmount'] = undefined;

/**
 * INCOME if surplus, EXPENSE if deficit, null if zero
 * @member {String} carryForwardType
 */
DailySummaryResponse.prototype['carryForwardType'] = undefined;

/**
 * @member {Array.<module:model/CashflowEntryResponse>} incomes
 */
DailySummaryResponse.prototype['incomes'] = undefined;

/**
 * @member {Array.<module:model/CashflowEntryResponse>} expenses
 */
DailySummaryResponse.prototype['expenses'] = undefined;






export default DailySummaryResponse;

