/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BillingType.
* @enum {}
* @readonly
*/
export default class BillingType {
    
        /**
         * value: "OFFICIAL"
         * @const
         */
        "OFFICIAL" = "OFFICIAL";

    
        /**
         * value: "OFFLINE"
         * @const
         */
        "OFFLINE" = "OFFLINE";

    

    /**
    * Returns a <code>BillingType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BillingType} The enum <code>BillingType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

