/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BillingType from './BillingType';
import FloorEnum from './FloorEnum';
import InvoiceStatus from './InvoiceStatus';
import OrderReplica from './OrderReplica';

/**
 * The Invoice model module.
 * @module model/Invoice
 * @version 1.0.0
 */
class Invoice {
    /**
     * Constructs a new <code>Invoice</code>.
     * @alias module:model/Invoice
     */
    constructor() { 
        
        Invoice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Invoice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Invoice} obj Optional instance to populate.
     * @return {module:model/Invoice} The populated <code>Invoice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Invoice();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = OrderReplica.constructFromObject(data['order']);
            }
            if (data.hasOwnProperty('invoiceStatus')) {
                obj['invoiceStatus'] = InvoiceStatus.constructFromObject(data['invoiceStatus']);
            }
            if (data.hasOwnProperty('floorEnum')) {
                obj['floorEnum'] = FloorEnum.constructFromObject(data['floorEnum']);
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = BillingType.constructFromObject(data['mode']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Invoice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Invoice</code>.
     */
    static validateJSON(data) {
        // validate the optional field `order`
        if (data['order']) { // data not null
          OrderReplica.validateJSON(data['order']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
Invoice.prototype['id'] = undefined;

/**
 * @member {module:model/OrderReplica} order
 */
Invoice.prototype['order'] = undefined;

/**
 * @member {module:model/InvoiceStatus} invoiceStatus
 */
Invoice.prototype['invoiceStatus'] = undefined;

/**
 * @member {module:model/FloorEnum} floorEnum
 */
Invoice.prototype['floorEnum'] = undefined;

/**
 * @member {module:model/BillingType} mode
 */
Invoice.prototype['mode'] = undefined;






export default Invoice;

