/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BillSummary from './BillSummary';
import OrderProductReplica from './OrderProductReplica';
import PaymentSummary from './PaymentSummary';

/**
 * The PartyLedgerOrder model module.
 * @module model/PartyLedgerOrder
 * @version 1.0.0
 */
class PartyLedgerOrder {
    /**
     * Constructs a new <code>PartyLedgerOrder</code>.
     * @alias module:model/PartyLedgerOrder
     */
    constructor() { 
        
        PartyLedgerOrder.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PartyLedgerOrder</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PartyLedgerOrder} obj Optional instance to populate.
     * @return {module:model/PartyLedgerOrder} The populated <code>PartyLedgerOrder</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartyLedgerOrder();

            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'Number');
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('billSummary')) {
                obj['billSummary'] = BillSummary.constructFromObject(data['billSummary']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [OrderProductReplica]);
            }
            if (data.hasOwnProperty('paymentSummary')) {
                obj['paymentSummary'] = PaymentSummary.constructFromObject(data['paymentSummary']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PartyLedgerOrder</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PartyLedgerOrder</code>.
     */
    static validateJSON(data) {
        // validate the optional field `billSummary`
        if (data['billSummary']) { // data not null
          BillSummary.validateJSON(data['billSummary']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                OrderProductReplica.validateJSON(item);
            };
        }
        // validate the optional field `paymentSummary`
        if (data['paymentSummary']) { // data not null
          PaymentSummary.validateJSON(data['paymentSummary']);
        }

        return true;
    }


}



/**
 * @member {Number} orderId
 */
PartyLedgerOrder.prototype['orderId'] = undefined;

/**
 * @member {Date} orderDate
 */
PartyLedgerOrder.prototype['orderDate'] = undefined;

/**
 * @member {module:model/BillSummary} billSummary
 */
PartyLedgerOrder.prototype['billSummary'] = undefined;

/**
 * @member {Array.<module:model/OrderProductReplica>} products
 */
PartyLedgerOrder.prototype['products'] = undefined;

/**
 * @member {module:model/PaymentSummary} paymentSummary
 */
PartyLedgerOrder.prototype['paymentSummary'] = undefined;






export default PartyLedgerOrder;

