/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentSide model module.
 * @module model/PaymentSide
 * @version 1.0.0
 */
class PaymentSide {
    /**
     * Constructs a new <code>PaymentSide</code>.
     * @alias module:model/PaymentSide
     */
    constructor() { 
        
        PaymentSide.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentSide</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentSide} obj Optional instance to populate.
     * @return {module:model/PaymentSide} The populated <code>PaymentSide</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentSide();

            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
            if (data.hasOwnProperty('receivedAmount')) {
                obj['receivedAmount'] = ApiClient.convertToType(data['receivedAmount'], 'Number');
            }
            if (data.hasOwnProperty('receivedDate')) {
                obj['receivedDate'] = ApiClient.convertToType(data['receivedDate'], 'Date');
            }
            if (data.hasOwnProperty('dueAmount')) {
                obj['dueAmount'] = ApiClient.convertToType(data['dueAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentSide</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentSide</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} totalAmount
 */
PaymentSide.prototype['totalAmount'] = undefined;

/**
 * @member {Number} receivedAmount
 */
PaymentSide.prototype['receivedAmount'] = undefined;

/**
 * @member {Date} receivedDate
 */
PaymentSide.prototype['receivedDate'] = undefined;

/**
 * @member {Number} dueAmount
 */
PaymentSide.prototype['dueAmount'] = undefined;






export default PaymentSide;

