/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentReceiveRequest model module.
 * @module model/PaymentReceiveRequest
 * @version 1.0.0
 */
class PaymentReceiveRequest {
    /**
     * Constructs a new <code>PaymentReceiveRequest</code>.
     * @alias module:model/PaymentReceiveRequest
     * @param newReceivedAmount {Number} 
     * @param newReceivedDate {Date} 
     */
    constructor(newReceivedAmount, newReceivedDate) { 
        
        PaymentReceiveRequest.initialize(this, newReceivedAmount, newReceivedDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, newReceivedAmount, newReceivedDate) { 
        obj['newReceivedAmount'] = newReceivedAmount;
        obj['newReceivedDate'] = newReceivedDate;
    }

    /**
     * Constructs a <code>PaymentReceiveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentReceiveRequest} obj Optional instance to populate.
     * @return {module:model/PaymentReceiveRequest} The populated <code>PaymentReceiveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentReceiveRequest();

            if (data.hasOwnProperty('newReceivedAmount')) {
                obj['newReceivedAmount'] = ApiClient.convertToType(data['newReceivedAmount'], 'Number');
            }
            if (data.hasOwnProperty('newReceivedDate')) {
                obj['newReceivedDate'] = ApiClient.convertToType(data['newReceivedDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentReceiveRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentReceiveRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentReceiveRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PaymentReceiveRequest.RequiredProperties = ["newReceivedAmount", "newReceivedDate"];

/**
 * @member {Number} newReceivedAmount
 */
PaymentReceiveRequest.prototype['newReceivedAmount'] = undefined;

/**
 * @member {Date} newReceivedDate
 */
PaymentReceiveRequest.prototype['newReceivedDate'] = undefined;






export default PaymentReceiveRequest;

