/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentSide from './PaymentSide';

/**
 * The PaymentSummary model module.
 * @module model/PaymentSummary
 * @version 1.0.0
 */
class PaymentSummary {
    /**
     * Constructs a new <code>PaymentSummary</code>.
     * @alias module:model/PaymentSummary
     */
    constructor() { 
        
        PaymentSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentSummary} obj Optional instance to populate.
     * @return {module:model/PaymentSummary} The populated <code>PaymentSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentSummary();

            if (data.hasOwnProperty('official')) {
                obj['official'] = PaymentSide.constructFromObject(data['official']);
            }
            if (data.hasOwnProperty('offline')) {
                obj['offline'] = PaymentSide.constructFromObject(data['offline']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentSummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentSummary</code>.
     */
    static validateJSON(data) {
        // validate the optional field `official`
        if (data['official']) { // data not null
          PaymentSide.validateJSON(data['official']);
        }
        // validate the optional field `offline`
        if (data['offline']) { // data not null
          PaymentSide.validateJSON(data['offline']);
        }

        return true;
    }


}



/**
 * @member {module:model/PaymentSide} official
 */
PaymentSummary.prototype['official'] = undefined;

/**
 * @member {module:model/PaymentSide} offline
 */
PaymentSummary.prototype['offline'] = undefined;






export default PaymentSummary;

