/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentStatus.
* @enum {}
* @readonly
*/
export default class PaymentStatus {
    
        /**
         * value: "OVERDUE"
         * @const
         */
        "OVERDUE" = "OVERDUE";

    
        /**
         * value: "DUE_SOON"
         * @const
         */
        "DUE_SOON" = "DUE_SOON";

    
        /**
         * value: "UPCOMING"
         * @const
         */
        "UPCOMING" = "UPCOMING";

    

    /**
    * Returns a <code>PaymentStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentStatus} The enum <code>PaymentStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

