/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentStatus from './PaymentStatus';

/**
 * The UpdatePaymentStatusRequest model module.
 * @module model/UpdatePaymentStatusRequest
 * @version 1.0.0
 */
class UpdatePaymentStatusRequest {
    /**
     * Constructs a new <code>UpdatePaymentStatusRequest</code>.
     * @alias module:model/UpdatePaymentStatusRequest
     * @param paymentStatus {module:model/PaymentStatus} 
     */
    constructor(paymentStatus) { 
        
        UpdatePaymentStatusRequest.initialize(this, paymentStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentStatus) { 
        obj['paymentStatus'] = paymentStatus;
    }

    /**
     * Constructs a <code>UpdatePaymentStatusRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdatePaymentStatusRequest} obj Optional instance to populate.
     * @return {module:model/UpdatePaymentStatusRequest} The populated <code>UpdatePaymentStatusRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePaymentStatusRequest();

            if (data.hasOwnProperty('paymentStatus')) {
                obj['paymentStatus'] = PaymentStatus.constructFromObject(data['paymentStatus']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdatePaymentStatusRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdatePaymentStatusRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdatePaymentStatusRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UpdatePaymentStatusRequest.RequiredProperties = ["paymentStatus"];

/**
 * @member {module:model/PaymentStatus} paymentStatus
 */
UpdatePaymentStatusRequest.prototype['paymentStatus'] = undefined;






export default UpdatePaymentStatusRequest;

