/**
 * User Management API
 * OpenAPI for Auth (signin, refresh) and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserGroup from './UserGroup';

/**
 * The UpdateUserGroupRequest model module.
 * @module model/UpdateUserGroupRequest
 * @version 1.0.0
 */
class UpdateUserGroupRequest {
    /**
     * Constructs a new <code>UpdateUserGroupRequest</code>.
     * @alias module:model/UpdateUserGroupRequest
     * @param userGroup {module:model/UserGroup} 
     */
    constructor(userGroup) { 
        
        UpdateUserGroupRequest.initialize(this, userGroup);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userGroup) { 
        obj['userGroup'] = userGroup;
    }

    /**
     * Constructs a <code>UpdateUserGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUserGroupRequest} obj Optional instance to populate.
     * @return {module:model/UpdateUserGroupRequest} The populated <code>UpdateUserGroupRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUserGroupRequest();

            if (data.hasOwnProperty('userGroup')) {
                obj['userGroup'] = UserGroup.constructFromObject(data['userGroup']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateUserGroupRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateUserGroupRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateUserGroupRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UpdateUserGroupRequest.RequiredProperties = ["userGroup"];

/**
 * @member {module:model/UserGroup} userGroup
 */
UpdateUserGroupRequest.prototype['userGroup'] = undefined;






export default UpdateUserGroupRequest;

