/**
 * User Management API
 * OpenAPI for Auth (signin, refresh) and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UserGroup.
* @enum {}
* @readonly
*/
export default class UserGroup {
    
        /**
         * value: "Admin"
         * @const
         */
        "Admin" = "Admin";

    
        /**
         * value: "Owner"
         * @const
         */
        "Owner" = "Owner";

    

    /**
    * Returns a <code>UserGroup</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UserGroup} The enum <code>UserGroup</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

