/**
 * User Management API
 * OpenAPI for Auth (signin, refresh) and user management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserGroup from './UserGroup';

/**
 * The UserRegistrationRequest model module.
 * @module model/UserRegistrationRequest
 * @version 1.0.0
 */
class UserRegistrationRequest {
    /**
     * Constructs a new <code>UserRegistrationRequest</code>.
     * @alias module:model/UserRegistrationRequest
     * @param email {String} User's email address (used as username)
     * @param password {String} Plain-text password (min 6 characters)
     * @param userGroup {module:model/UserGroup} 
     */
    constructor(email, password, userGroup) { 
        
        UserRegistrationRequest.initialize(this, email, password, userGroup);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, password, userGroup) { 
        obj['email'] = email;
        obj['password'] = password;
        obj['userGroup'] = userGroup;
    }

    /**
     * Constructs a <code>UserRegistrationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserRegistrationRequest} obj Optional instance to populate.
     * @return {module:model/UserRegistrationRequest} The populated <code>UserRegistrationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserRegistrationRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('userGroup')) {
                obj['userGroup'] = UserGroup.constructFromObject(data['userGroup']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserRegistrationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserRegistrationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserRegistrationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

UserRegistrationRequest.RequiredProperties = ["email", "password", "userGroup"];

/**
 * User's email address (used as username)
 * @member {String} email
 */
UserRegistrationRequest.prototype['email'] = undefined;

/**
 * Plain-text password (min 6 characters)
 * @member {String} password
 */
UserRegistrationRequest.prototype['password'] = undefined;

/**
 * @member {module:model/UserGroup} userGroup
 */
UserRegistrationRequest.prototype['userGroup'] = undefined;






export default UserRegistrationRequest;

