/**
 * Invoice & Payment API
 * OpenAPI for Invoice And Payment management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BillingType from '../model/BillingType';
import FloorEnum from '../model/FloorEnum';
import PaginatedResultPayment from '../model/PaginatedResultPayment';
import PartyLedgerResponse from '../model/PartyLedgerResponse';
import Payment from '../model/Payment';
import PaymentReceiveRequest from '../model/PaymentReceiveRequest';
import UpdatePaymentStatusRequest from '../model/UpdatePaymentStatusRequest';

/**
* Payments service.
* @module api/PaymentsApi
* @version 1.0.0
*/
export default class PaymentsApi {

    /**
    * Constructs a new PaymentsApi. 
    * @alias module:api/PaymentsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deletePayment operation.
     * @callback module:api/PaymentsApi~deletePaymentCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete payment by ID
     * @param {Number} paymentId 
     * @param {module:api/PaymentsApi~deletePaymentCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePayment(paymentId, callback) {
      let postBody = null;
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling deletePayment");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPartyLedger operation.
     * @callback module:api/PaymentsApi~getPartyLedgerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PartyLedgerResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get comprehensive party ledger with order details
     * @param {Number} partyId 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @param {module:api/PaymentsApi~getPartyLedgerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PartyLedgerResponse}
     */
    getPartyLedger(partyId, startDate, endDate, callback) {
      let postBody = null;
      // verify the required parameter 'partyId' is set
      if (partyId === undefined || partyId === null) {
        throw new Error("Missing the required parameter 'partyId' when calling getPartyLedger");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getPartyLedger");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getPartyLedger");
      }

      let pathParams = {
        'partyId': partyId
      };
      let queryParams = {
        'startDate': startDate,
        'endDate': endDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PartyLedgerResponse;
      return this.apiClient.callApi(
        '/api/v1/payments/party-ledger/{partyId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPartyLedgerPdf operation.
     * @callback module:api/PaymentsApi~getPartyLedgerPdfCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get comprehensive party ledger as PDF
     * @param {Number} partyId 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @param {module:api/PaymentsApi~getPartyLedgerPdfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    getPartyLedgerPdf(partyId, startDate, endDate, callback) {
      let postBody = null;
      // verify the required parameter 'partyId' is set
      if (partyId === undefined || partyId === null) {
        throw new Error("Missing the required parameter 'partyId' when calling getPartyLedgerPdf");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getPartyLedgerPdf");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getPartyLedgerPdf");
      }

      let pathParams = {
        'partyId': partyId
      };
      let queryParams = {
        'startDate': startDate,
        'endDate': endDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/payments/party-ledger/{partyId}/pdf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPaymentById operation.
     * @callback module:api/PaymentsApi~getPaymentByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get payment by ID
     * @param {Number} paymentId 
     * @param {module:api/PaymentsApi~getPaymentByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payment}
     */
    getPaymentById(paymentId, callback) {
      let postBody = null;
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling getPaymentById");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Payment;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPaymentByOrderAndMode operation.
     * @callback module:api/PaymentsApi~getPaymentByOrderAndModeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get payment by main order ID and billing mode
     * @param {Number} orderId 
     * @param {module:model/BillingType} mode 
     * @param {module:api/PaymentsApi~getPaymentByOrderAndModeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payment}
     */
    getPaymentByOrderAndMode(orderId, mode, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling getPaymentByOrderAndMode");
      }
      // verify the required parameter 'mode' is set
      if (mode === undefined || mode === null) {
        throw new Error("Missing the required parameter 'mode' when calling getPaymentByOrderAndMode");
      }

      let pathParams = {
        'orderId': orderId,
        'mode': mode
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Payment;
      return this.apiClient.callApi(
        '/api/v1/payments/order/{orderId}/mode/{mode}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPaymentsByFloor operation.
     * @callback module:api/PaymentsApi~getPaymentsByFloorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResultPayment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get paginated list of payments by floor
     * @param {module:model/FloorEnum} floor 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page number starting from 0
     * @param {Number} [size = 10)] Number of items per page
     * @param {String} [status] Filter by payment status
     * @param {String} [search] Filter by Order id and customer name
     * @param {module:model/String} [sortByFields] Field to sort by
     * @param {module:model/String} [direction] Sort direction
     * @param {module:api/PaymentsApi~getPaymentsByFloorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResultPayment}
     */
    getPaymentsByFloor(floor, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'floor' is set
      if (floor === undefined || floor === null) {
        throw new Error("Missing the required parameter 'floor' when calling getPaymentsByFloor");
      }

      let pathParams = {
        'floor': floor
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'status': opts['status'],
        'search': opts['search'],
        'sortByFields': opts['sortByFields'],
        'direction': opts['direction']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedResultPayment;
      return this.apiClient.callApi(
        '/api/v1/payments/floor/{floor}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the receivePayment operation.
     * @callback module:api/PaymentsApi~receivePaymentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update received payment details
     * Updates received amount and received dates for a payment. Existing received amount is incremented with new received amount. 
     * @param {Number} paymentId 
     * @param {module:model/PaymentReceiveRequest} paymentReceiveRequest 
     * @param {module:api/PaymentsApi~receivePaymentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payment}
     */
    receivePayment(paymentId, paymentReceiveRequest, callback) {
      let postBody = paymentReceiveRequest;
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling receivePayment");
      }
      // verify the required parameter 'paymentReceiveRequest' is set
      if (paymentReceiveRequest === undefined || paymentReceiveRequest === null) {
        throw new Error("Missing the required parameter 'paymentReceiveRequest' when calling receivePayment");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Payment;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}/receive', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the sendManualReminder operation.
     * @callback module:api/PaymentsApi~sendManualReminderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send manual payment reminder
     * Triggers a payment reminder via WhatsApp and Email for the specified payment.
     * @param {Number} paymentId 
     * @param {module:api/PaymentsApi~sendManualReminderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    sendManualReminder(paymentId, callback) {
      let postBody = null;
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling sendManualReminder");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}/reminder', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePaymentStatus operation.
     * @callback module:api/PaymentsApi~updatePaymentStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Payment} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update payment status
     * @param {Number} paymentId 
     * @param {module:model/UpdatePaymentStatusRequest} updatePaymentStatusRequest 
     * @param {module:api/PaymentsApi~updatePaymentStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Payment}
     */
    updatePaymentStatus(paymentId, updatePaymentStatusRequest, callback) {
      let postBody = updatePaymentStatusRequest;
      // verify the required parameter 'paymentId' is set
      if (paymentId === undefined || paymentId === null) {
        throw new Error("Missing the required parameter 'paymentId' when calling updatePaymentStatus");
      }
      // verify the required parameter 'updatePaymentStatusRequest' is set
      if (updatePaymentStatusRequest === undefined || updatePaymentStatusRequest === null) {
        throw new Error("Missing the required parameter 'updatePaymentStatusRequest' when calling updatePaymentStatus");
      }

      let pathParams = {
        'paymentId': paymentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Payment;
      return this.apiClient.callApi(
        '/api/v1/payments/{paymentId}/status', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
