/**
 * Forging API
 * OpenAPI for Forging Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ForgingItemRequest model module.
 * @module model/ForgingItemRequest
 * @version 1.0.0
 */
class ForgingItemRequest {
    /**
     * Constructs a new <code>ForgingItemRequest</code>.
     * @alias module:model/ForgingItemRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        ForgingItemRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ForgingItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForgingItemRequest} obj Optional instance to populate.
     * @return {module:model/ForgingItemRequest} The populated <code>ForgingItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForgingItemRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('pricePerKg')) {
                obj['pricePerKg'] = ApiClient.convertToType(data['pricePerKg'], 'Number');
            }
            if (data.hasOwnProperty('lowStockAlert')) {
                obj['lowStockAlert'] = ApiClient.convertToType(data['lowStockAlert'], 'Number');
            }
            if (data.hasOwnProperty('quantityInPc')) {
                obj['quantityInPc'] = ApiClient.convertToType(data['quantityInPc'], 'Number');
            }
            if (data.hasOwnProperty('weightPerPc')) {
                obj['weightPerPc'] = ApiClient.convertToType(data['weightPerPc'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForgingItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForgingItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ForgingItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ForgingItemRequest.RequiredProperties = ["name"];

/**
 * @member {String} name
 */
ForgingItemRequest.prototype['name'] = undefined;

/**
 * Price per KG for inventory valuation
 * @member {Number} pricePerKg
 */
ForgingItemRequest.prototype['pricePerKg'] = undefined;

/**
 * Low stock threshold in KG to trigger alert
 * @member {Number} lowStockAlert
 */
ForgingItemRequest.prototype['lowStockAlert'] = undefined;

/**
 * Quantity in pieces (optional)
 * @member {Number} quantityInPc
 */
ForgingItemRequest.prototype['quantityInPc'] = undefined;

/**
 * Weight per piece in KG; if set, piece count is auto-calculated from KG
 * @member {Number} weightPerPc
 */
ForgingItemRequest.prototype['weightPerPc'] = undefined;






export default ForgingItemRequest;

