/**
 * Forging API
 * OpenAPI for Forging Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OutwardWeightUnit from './OutwardWeightUnit';
import Party from './Party';

/**
 * The ForgingOutward model module.
 * @module model/ForgingOutward
 * @version 1.0.0
 */
class ForgingOutward {
    /**
     * Constructs a new <code>ForgingOutward</code>.
     * @alias module:model/ForgingOutward
     */
    constructor() { 
        
        ForgingOutward.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ForgingOutward</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ForgingOutward} obj Optional instance to populate.
     * @return {module:model/ForgingOutward} The populated <code>ForgingOutward</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ForgingOutward();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('party')) {
                obj['party'] = Party.constructFromObject(data['party']);
            }
            if (data.hasOwnProperty('challanNo')) {
                obj['challanNo'] = ApiClient.convertToType(data['challanNo'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('weightUnit')) {
                obj['weightUnit'] = OutwardWeightUnit.constructFromObject(data['weightUnit']);
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ForgingOutward</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ForgingOutward</code>.
     */
    static validateJSON(data) {
        // validate the optional field `party`
        if (data['party']) { // data not null
          Party.validateJSON(data['party']);
        }
        // ensure the json data is a string
        if (data['challanNo'] && !(typeof data['challanNo'] === 'string' || data['challanNo'] instanceof String)) {
            throw new Error("Expected the field `challanNo` to be a primitive type in the JSON string but got " + data['challanNo']);
        }
        // ensure the json data is a string
        if (data['image'] && !(typeof data['image'] === 'string' || data['image'] instanceof String)) {
            throw new Error("Expected the field `image` to be a primitive type in the JSON string but got " + data['image']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ForgingOutward.prototype['id'] = undefined;

/**
 * @member {module:model/Party} party
 */
ForgingOutward.prototype['party'] = undefined;

/**
 * @member {String} challanNo
 */
ForgingOutward.prototype['challanNo'] = undefined;

/**
 * @member {Date} date
 */
ForgingOutward.prototype['date'] = undefined;

/**
 * @member {Number} weight
 */
ForgingOutward.prototype['weight'] = undefined;

/**
 * @member {module:model/OutwardWeightUnit} weightUnit
 */
ForgingOutward.prototype['weightUnit'] = undefined;

/**
 * @member {String} image
 */
ForgingOutward.prototype['image'] = undefined;






export default ForgingOutward;

