/**
 * Forging API
 * OpenAPI for Forging Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class InwardWeightUnit.
* @enum {}
* @readonly
*/
export default class InwardWeightUnit {
    
        /**
         * value: "CHHOL"
         * @const
         */
        "CHHOL" = "CHHOL";

    
        /**
         * value: "KG"
         * @const
         */
        "KG" = "KG";

    
        /**
         * value: "TAIYAR MAAL"
         * @const
         */
        "TAIYAR MAAL" = "TAIYAR MAAL";

    
        /**
         * value: "REJECTION"
         * @const
         */
        "REJECTION" = "REJECTION";

    

    /**
    * Returns a <code>InwardWeightUnit</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InwardWeightUnit} The enum <code>InwardWeightUnit</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

