/**
 * Forging API
 * OpenAPI for Forging Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OutwardWeightUnit.
* @enum {}
* @readonly
*/
export default class OutwardWeightUnit {
    
        /**
         * value: "WIRE"
         * @const
         */
        "WIRE" = "WIRE";

    

    /**
    * Returns a <code>OutwardWeightUnit</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OutwardWeightUnit} The enum <code>OutwardWeightUnit</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

