/**
 * Electric API
 * OpenAPI for Electric Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ElectricOutward model module.
 * @module model/ElectricOutward
 * @version 1.0.0
 */
class ElectricOutward {
    /**
     * Constructs a new <code>ElectricOutward</code>.
     * @alias module:model/ElectricOutward
     */
    constructor() { 
        
        ElectricOutward.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ElectricOutward</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ElectricOutward} obj Optional instance to populate.
     * @return {module:model/ElectricOutward} The populated <code>ElectricOutward</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ElectricOutward();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('challanNo')) {
                obj['challanNo'] = ApiClient.convertToType(data['challanNo'], 'String');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('perKgWeight')) {
                obj['perKgWeight'] = ApiClient.convertToType(data['perKgWeight'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'Number');
            }
            if (data.hasOwnProperty('unitRate')) {
                obj['unitRate'] = ApiClient.convertToType(data['unitRate'], 'Number');
            }
            if (data.hasOwnProperty('totalUnitAmount')) {
                obj['totalUnitAmount'] = ApiClient.convertToType(data['totalUnitAmount'], 'Number');
            }
            if (data.hasOwnProperty('totalWeightAmount')) {
                obj['totalWeightAmount'] = ApiClient.convertToType(data['totalWeightAmount'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ElectricOutward</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ElectricOutward</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['challanNo'] && !(typeof data['challanNo'] === 'string' || data['challanNo'] instanceof String)) {
            throw new Error("Expected the field `challanNo` to be a primitive type in the JSON string but got " + data['challanNo']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ElectricOutward.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
ElectricOutward.prototype['date'] = undefined;

/**
 * @member {String} challanNo
 */
ElectricOutward.prototype['challanNo'] = undefined;

/**
 * @member {Number} weight
 */
ElectricOutward.prototype['weight'] = undefined;

/**
 * @member {Number} perKgWeight
 */
ElectricOutward.prototype['perKgWeight'] = undefined;

/**
 * @member {Number} unit
 */
ElectricOutward.prototype['unit'] = undefined;

/**
 * @member {Number} unitRate
 */
ElectricOutward.prototype['unitRate'] = undefined;

/**
 * @member {Number} totalUnitAmount
 */
ElectricOutward.prototype['totalUnitAmount'] = undefined;

/**
 * @member {Number} totalWeightAmount
 */
ElectricOutward.prototype['totalWeightAmount'] = undefined;

/**
 * @member {Number} totalAmount
 */
ElectricOutward.prototype['totalAmount'] = undefined;






export default ElectricOutward;

