/**
 * Electric API
 * OpenAPI for Electric Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ElectricOutwardRequest model module.
 * @module model/ElectricOutwardRequest
 * @version 1.0.0
 */
class ElectricOutwardRequest {
    /**
     * Constructs a new <code>ElectricOutwardRequest</code>.
     * @alias module:model/ElectricOutwardRequest
     */
    constructor() { 
        
        ElectricOutwardRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ElectricOutwardRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ElectricOutwardRequest} obj Optional instance to populate.
     * @return {module:model/ElectricOutwardRequest} The populated <code>ElectricOutwardRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ElectricOutwardRequest();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('challanNo')) {
                obj['challanNo'] = ApiClient.convertToType(data['challanNo'], 'String');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('perKgWeight')) {
                obj['perKgWeight'] = ApiClient.convertToType(data['perKgWeight'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'Number');
            }
            if (data.hasOwnProperty('unitRate')) {
                obj['unitRate'] = ApiClient.convertToType(data['unitRate'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ElectricOutwardRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ElectricOutwardRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['challanNo'] && !(typeof data['challanNo'] === 'string' || data['challanNo'] instanceof String)) {
            throw new Error("Expected the field `challanNo` to be a primitive type in the JSON string but got " + data['challanNo']);
        }

        return true;
    }


}



/**
 * @member {Date} date
 */
ElectricOutwardRequest.prototype['date'] = undefined;

/**
 * @member {String} challanNo
 */
ElectricOutwardRequest.prototype['challanNo'] = undefined;

/**
 * @member {Number} weight
 */
ElectricOutwardRequest.prototype['weight'] = undefined;

/**
 * @member {Number} perKgWeight
 */
ElectricOutwardRequest.prototype['perKgWeight'] = undefined;

/**
 * @member {Number} unit
 */
ElectricOutwardRequest.prototype['unit'] = undefined;

/**
 * @member {Number} unitRate
 */
ElectricOutwardRequest.prototype['unitRate'] = undefined;






export default ElectricOutwardRequest;

