/**
 * Electric API
 * OpenAPI for Electric Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ElectricCreditRequest model module.
 * @module model/ElectricCreditRequest
 * @version 1.0.0
 */
class ElectricCreditRequest {
    /**
     * Constructs a new <code>ElectricCreditRequest</code>.
     * @alias module:model/ElectricCreditRequest
     */
    constructor() { 
        
        ElectricCreditRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ElectricCreditRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ElectricCreditRequest} obj Optional instance to populate.
     * @return {module:model/ElectricCreditRequest} The populated <code>ElectricCreditRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ElectricCreditRequest();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('challanNo')) {
                obj['challanNo'] = ApiClient.convertToType(data['challanNo'], 'String');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ElectricCreditRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ElectricCreditRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['challanNo'] && !(typeof data['challanNo'] === 'string' || data['challanNo'] instanceof String)) {
            throw new Error("Expected the field `challanNo` to be a primitive type in the JSON string but got " + data['challanNo']);
        }

        return true;
    }


}



/**
 * @member {Date} date
 */
ElectricCreditRequest.prototype['date'] = undefined;

/**
 * @member {String} challanNo
 */
ElectricCreditRequest.prototype['challanNo'] = undefined;

/**
 * @member {Number} rate
 */
ElectricCreditRequest.prototype['rate'] = undefined;






export default ElectricCreditRequest;

