/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CloseDayResponse from '../model/CloseDayResponse';
import DailySummaryResponse from '../model/DailySummaryResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* CashflowSummary service.
* @module api/CashflowSummaryApi
* @version 1.0.0
*/
export default class CashflowSummaryApi {

    /**
    * Constructs a new CashflowSummaryApi. 
    * @alias module:api/CashflowSummaryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the closeDay operation.
     * @callback module:api/CashflowSummaryApi~closeDayCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CloseDayResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Close a day and carry forward the balance to the next day
     * @param {Object} opts Optional parameters
     * @param {Date} [date] Filter by date (yyyy-MM-dd)
     * @param {module:api/CashflowSummaryApi~closeDayCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CloseDayResponse}
     */
    closeDay(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'date': opts['date']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CloseDayResponse;
      return this.apiClient.callApi(
        '/api/v1/cashflow/close-day', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDailySummary operation.
     * @callback module:api/CashflowSummaryApi~getDailySummaryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DailySummaryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get daily summary with totals and carry-forward preview
     * @param {Object} opts Optional parameters
     * @param {Date} [date] Filter by date (yyyy-MM-dd)
     * @param {module:api/CashflowSummaryApi~getDailySummaryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DailySummaryResponse}
     */
    getDailySummary(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'date': opts['date']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DailySummaryResponse;
      return this.apiClient.callApi(
        '/api/v1/cashflow/summary', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
