/**
 * Cashflow API
 * Daily income and expense cashflow management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CashflowEntryRequest from '../model/CashflowEntryRequest';
import CashflowEntryResponse from '../model/CashflowEntryResponse';
import ErrorResponse from '../model/ErrorResponse';
import PaginatedCashflowEntry from '../model/PaginatedCashflowEntry';

/**
* CashflowIncome service.
* @module api/CashflowIncomeApi
* @version 1.0.0
*/
export default class CashflowIncomeApi {

    /**
    * Constructs a new CashflowIncomeApi. 
    * @alias module:api/CashflowIncomeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addIncome operation.
     * @callback module:api/CashflowIncomeApi~addIncomeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CashflowEntryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add an income entry
     * @param {module:model/CashflowEntryRequest} cashflowEntryRequest 
     * @param {module:api/CashflowIncomeApi~addIncomeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CashflowEntryResponse}
     */
    addIncome(cashflowEntryRequest, callback) {
      let postBody = cashflowEntryRequest;
      // verify the required parameter 'cashflowEntryRequest' is set
      if (cashflowEntryRequest === undefined || cashflowEntryRequest === null) {
        throw new Error("Missing the required parameter 'cashflowEntryRequest' when calling addIncome");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CashflowEntryResponse;
      return this.apiClient.callApi(
        '/api/v1/cashflow/income', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteIncome operation.
     * @callback module:api/CashflowIncomeApi~deleteIncomeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an income entry
     * @param {Number} id 
     * @param {module:api/CashflowIncomeApi~deleteIncomeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteIncome(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteIncome");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/cashflow/income/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getIncomeList operation.
     * @callback module:api/CashflowIncomeApi~getIncomeListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedCashflowEntry} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get paginated income entries
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 10)] 
     * @param {Date} [date] Filter by date (yyyy-MM-dd)
     * @param {module:api/CashflowIncomeApi~getIncomeListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedCashflowEntry}
     */
    getIncomeList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'date': opts['date']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedCashflowEntry;
      return this.apiClient.callApi(
        '/api/v1/cashflow/income', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateIncome operation.
     * @callback module:api/CashflowIncomeApi~updateIncomeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CashflowEntryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an income entry
     * @param {Number} id 
     * @param {module:model/CashflowEntryRequest} cashflowEntryRequest 
     * @param {module:api/CashflowIncomeApi~updateIncomeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CashflowEntryResponse}
     */
    updateIncome(id, cashflowEntryRequest, callback) {
      let postBody = cashflowEntryRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateIncome");
      }
      // verify the required parameter 'cashflowEntryRequest' is set
      if (cashflowEntryRequest === undefined || cashflowEntryRequest === null) {
        throw new Error("Missing the required parameter 'cashflowEntryRequest' when calling updateIncome");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CashflowEntryResponse;
      return this.apiClient.callApi(
        '/api/v1/cashflow/income/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
