/**
 * Forging API
 * OpenAPI for Forging Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import ForgingInward from '../model/ForgingInward';
import ForgingInwardRequest from '../model/ForgingInwardRequest';
import PaginatedForgingInwardResponse from '../model/PaginatedForgingInwardResponse';

/**
* ForgingInward service.
* @module api/ForgingInwardApi
* @version 1.0.0
*/
export default class ForgingInwardApi {

    /**
    * Constructs a new ForgingInwardApi. 
    * @alias module:api/ForgingInwardApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createForgingInward operation.
     * @callback module:api/ForgingInwardApi~createForgingInwardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ForgingInward} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Forging Inward record
     * @param {module:model/ForgingInwardRequest} forgingInwardRequest 
     * @param {module:api/ForgingInwardApi~createForgingInwardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ForgingInward}
     */
    createForgingInward(forgingInwardRequest, callback) {
      let postBody = forgingInwardRequest;
      // verify the required parameter 'forgingInwardRequest' is set
      if (forgingInwardRequest === undefined || forgingInwardRequest === null) {
        throw new Error("Missing the required parameter 'forgingInwardRequest' when calling createForgingInward");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ForgingInward;
      return this.apiClient.callApi(
        '/api/v1/forging-inward', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteForgingInward operation.
     * @callback module:api/ForgingInwardApi~deleteForgingInwardCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/ForgingInwardApi~deleteForgingInwardCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteForgingInward(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteForgingInward");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/forging-inward/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getForgingInwardById operation.
     * @callback module:api/ForgingInwardApi~getForgingInwardByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ForgingInward} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/ForgingInwardApi~getForgingInwardByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ForgingInward}
     */
    getForgingInwardById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getForgingInwardById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ForgingInward;
      return this.apiClient.callApi(
        '/api/v1/forging-inward/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchForgingInwards operation.
     * @callback module:api/ForgingInwardApi~searchForgingInwardsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedForgingInwardResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List/Search Forging Inward records
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 10)] 
     * @param {Date} [fromDate] 
     * @param {Date} [toDate] 
     * @param {module:api/ForgingInwardApi~searchForgingInwardsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedForgingInwardResponse}
     */
    searchForgingInwards(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'fromDate': opts['fromDate'],
        'toDate': opts['toDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedForgingInwardResponse;
      return this.apiClient.callApi(
        '/api/v1/forging-inward', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateForgingInward operation.
     * @callback module:api/ForgingInwardApi~updateForgingInwardCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ForgingInward} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/ForgingInwardRequest} forgingInwardRequest 
     * @param {module:api/ForgingInwardApi~updateForgingInwardCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ForgingInward}
     */
    updateForgingInward(id, forgingInwardRequest, callback) {
      let postBody = forgingInwardRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateForgingInward");
      }
      // verify the required parameter 'forgingInwardRequest' is set
      if (forgingInwardRequest === undefined || forgingInwardRequest === null) {
        throw new Error("Missing the required parameter 'forgingInwardRequest' when calling updateForgingInward");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ForgingInward;
      return this.apiClient.callApi(
        '/api/v1/forging-inward/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
