/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NewPurchaseParty from '../model/NewPurchaseParty';
import PurchaseParty from '../model/PurchaseParty';

/**
* PurchaseParty service.
* @module api/PurchasePartyApi
* @version 1.0.0
*/
export default class PurchasePartyApi {

    /**
    * Constructs a new PurchasePartyApi. 
    * @alias module:api/PurchasePartyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createPurchaseParty operation.
     * @callback module:api/PurchasePartyApi~createPurchasePartyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PurchaseParty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create purchase party
     * @param {module:model/NewPurchaseParty} newPurchaseParty 
     * @param {module:api/PurchasePartyApi~createPurchasePartyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PurchaseParty}
     */
    createPurchaseParty(newPurchaseParty, callback) {
      let postBody = newPurchaseParty;
      // verify the required parameter 'newPurchaseParty' is set
      if (newPurchaseParty === undefined || newPurchaseParty === null) {
        throw new Error("Missing the required parameter 'newPurchaseParty' when calling createPurchaseParty");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PurchaseParty;
      return this.apiClient.callApi(
        '/api/v1/purchase/parties', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePurchaseParty operation.
     * @callback module:api/PurchasePartyApi~deletePurchasePartyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete purchase party
     * @param {Number} id 
     * @param {module:api/PurchasePartyApi~deletePurchasePartyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePurchaseParty(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deletePurchaseParty");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/purchase/parties/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllPurchaseParties operation.
     * @callback module:api/PurchasePartyApi~getAllPurchasePartiesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PurchaseParty>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all purchase parties
     * @param {Object} opts Optional parameters
     * @param {String} [search] 
     * @param {module:api/PurchasePartyApi~getAllPurchasePartiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PurchaseParty>}
     */
    getAllPurchaseParties(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PurchaseParty];
      return this.apiClient.callApi(
        '/api/v1/purchase/parties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPurchasePartyById operation.
     * @callback module:api/PurchasePartyApi~getPurchasePartyByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PurchaseParty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get purchase party by id
     * @param {Number} id 
     * @param {module:api/PurchasePartyApi~getPurchasePartyByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PurchaseParty}
     */
    getPurchasePartyById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPurchasePartyById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PurchaseParty;
      return this.apiClient.callApi(
        '/api/v1/purchase/parties/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePurchaseParty operation.
     * @callback module:api/PurchasePartyApi~updatePurchasePartyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PurchaseParty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update purchase party
     * @param {Number} id 
     * @param {module:model/NewPurchaseParty} newPurchaseParty 
     * @param {module:api/PurchasePartyApi~updatePurchasePartyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PurchaseParty}
     */
    updatePurchaseParty(id, newPurchaseParty, callback) {
      let postBody = newPurchaseParty;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updatePurchaseParty");
      }
      // verify the required parameter 'newPurchaseParty' is set
      if (newPurchaseParty === undefined || newPurchaseParty === null) {
        throw new Error("Missing the required parameter 'newPurchaseParty' when calling updatePurchaseParty");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PurchaseParty;
      return this.apiClient.callApi(
        '/api/v1/purchase/parties/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
