/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import PaginatedResultRawItem from '../model/PaginatedResultRawItem';
import RawItem from '../model/RawItem';
import RawItemRequest from '../model/RawItemRequest';
import UpdateStockItemStatusRequest from '../model/UpdateStockItemStatusRequest';

/**
* RawInventory service.
* @module api/RawInventoryApi
* @version 1.0.0
*/
export default class RawInventoryApi {

    /**
    * Constructs a new RawInventoryApi. 
    * @alias module:api/RawInventoryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addRawItem operation.
     * @callback module:api/RawInventoryApi~addRawItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RawItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Raw Item
     * Adds a new Raw Item into the system.
     * @param {module:model/RawItemRequest} rawItemRequest 
     * @param {module:api/RawInventoryApi~addRawItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RawItem}
     */
    addRawItem(rawItemRequest, callback) {
      let postBody = rawItemRequest;
      // verify the required parameter 'rawItemRequest' is set
      if (rawItemRequest === undefined || rawItemRequest === null) {
        throw new Error("Missing the required parameter 'rawItemRequest' when calling addRawItem");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RawItem;
      return this.apiClient.callApi(
        '/api/v1/raw-item', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteRawItem operation.
     * @callback module:api/RawInventoryApi~deleteRawItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Raw Item
     * Deletes a single Raw item based on its ID.
     * @param {Number} rawItemId 
     * @param {module:api/RawInventoryApi~deleteRawItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteRawItem(rawItemId, callback) {
      let postBody = null;
      // verify the required parameter 'rawItemId' is set
      if (rawItemId === undefined || rawItemId === null) {
        throw new Error("Missing the required parameter 'rawItemId' when calling deleteRawItem");
      }

      let pathParams = {
        'rawItemId': rawItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/raw-item/{rawItemId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRawItemById operation.
     * @callback module:api/RawInventoryApi~getRawItemByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RawItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Raw item by ID
     * Returns a single Raw item based on its ID.
     * @param {Number} rawItemId 
     * @param {module:api/RawInventoryApi~getRawItemByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RawItem}
     */
    getRawItemById(rawItemId, callback) {
      let postBody = null;
      // verify the required parameter 'rawItemId' is set
      if (rawItemId === undefined || rawItemId === null) {
        throw new Error("Missing the required parameter 'rawItemId' when calling getRawItemById");
      }

      let pathParams = {
        'rawItemId': rawItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RawItem;
      return this.apiClient.callApi(
        '/api/v1/raw-item/{rawItemId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getRawItemList operation.
     * @callback module:api/RawInventoryApi~getRawItemListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResultRawItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Raw items with pagination
     * Returns a paginated list of all Raw items.
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page number starting from 0
     * @param {Number} [size = 10)] Number of items per page
     * @param {module:model/String} [status] Filter by status
     * @param {String} [search] 
     * @param {module:model/String} [sortByFields] Field to sort by
     * @param {module:model/String} [direction] Sort direction
     * @param {module:api/RawInventoryApi~getRawItemListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResultRawItem}
     */
    getRawItemList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'status': opts['status'],
        'search': opts['search'],
        'sortByFields': opts['sortByFields'],
        'direction': opts['direction']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedResultRawItem;
      return this.apiClient.callApi(
        '/api/v1/raw-item', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateRawItem operation.
     * @callback module:api/RawInventoryApi~updateRawItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RawItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Raw Item
     * Updates an existing Raw Item in the system.
     * @param {Number} rawItemId 
     * @param {module:model/RawItemRequest} rawItemRequest 
     * @param {module:api/RawInventoryApi~updateRawItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RawItem}
     */
    updateRawItem(rawItemId, rawItemRequest, callback) {
      let postBody = rawItemRequest;
      // verify the required parameter 'rawItemId' is set
      if (rawItemId === undefined || rawItemId === null) {
        throw new Error("Missing the required parameter 'rawItemId' when calling updateRawItem");
      }
      // verify the required parameter 'rawItemRequest' is set
      if (rawItemRequest === undefined || rawItemRequest === null) {
        throw new Error("Missing the required parameter 'rawItemRequest' when calling updateRawItem");
      }

      let pathParams = {
        'rawItemId': rawItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = RawItem;
      return this.apiClient.callApi(
        '/api/v1/raw-item/{rawItemId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateRawItemStatus operation.
     * @callback module:api/RawInventoryApi~updateRawItemStatusCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update raw item order status
     * Updates only the status of a raw item.
     * @param {Number} rawItemId 
     * @param {module:model/UpdateStockItemStatusRequest} updateStockItemStatusRequest 
     * @param {module:api/RawInventoryApi~updateRawItemStatusCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateRawItemStatus(rawItemId, updateStockItemStatusRequest, callback) {
      let postBody = updateStockItemStatusRequest;
      // verify the required parameter 'rawItemId' is set
      if (rawItemId === undefined || rawItemId === null) {
        throw new Error("Missing the required parameter 'rawItemId' when calling updateRawItemStatus");
      }
      // verify the required parameter 'updateStockItemStatusRequest' is set
      if (updateStockItemStatusRequest === undefined || updateStockItemStatusRequest === null) {
        throw new Error("Missing the required parameter 'updateStockItemStatusRequest' when calling updateRawItemStatus");
      }

      let pathParams = {
        'rawItemId': rawItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/raw-item/{rawItemId}/status', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
