openapi: 3.0.3
info:
  title: Electric API
  version: 1.0.0
  description: OpenAPI for Electric Management
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: ElectricOutward
    description: Electric Outward Management
  - name: ElectricCredit
    description: Electric Credit Management

paths:
  /api/v1/electric-outward:
    post:
      tags:
        - ElectricOutward
      operationId: createElectricOutward
      summary: Create Electric Outward record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElectricOutwardRequest'
      responses:
        '201':
          description: Electric Outward created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectricOutward'
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]

    get:
      tags:
        - ElectricOutward
      operationId: searchElectricOutwards
      summary: List/Search Electric Outward records
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of Electric Outward records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedElectricOutwardResponse'
      security:
        - oauth2: [ ]

  /api/v1/electric-outward/export/pdf:
    get:
      tags:
        - ElectricOutward
      operationId: exportElectricOutwardPdf
      summary: Export Electric Outward records to PDF
      parameters:
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: PDF file generated
          content:
            application/pdf:
              schema:
                type: string
                format: binary
      security:
        - oauth2: [ ]

  /api/v1/electric-outward/{id}:
    get:
      tags:
        - ElectricOutward
      operationId: getElectricOutwardById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Electric Outward details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectricOutward'
      security:
        - oauth2: [ ]
    put:
      tags:
        - ElectricOutward
      operationId: updateElectricOutward
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElectricOutwardRequest'
      responses:
        '200':
          description: Updated Electric Outward
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectricOutward'
      security:
        - oauth2: [ ]
    delete:
      tags:
        - ElectricOutward
      operationId: deleteElectricOutward
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted
      security:
        - oauth2: [ ]

  /api/v1/electric-credit:
    post:
      tags:
        - ElectricCredit
      operationId: createElectricCredit
      summary: Create Electric Credit record
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElectricCreditRequest'
      responses:
        '201':
          description: Electric Credit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectricCredit'
        '400':
          description: Invalid Input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]

    get:
      tags:
        - ElectricCredit
      operationId: searchElectricCredits
      summary: List/Search Electric Credit records
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of Electric Credit records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedElectricCreditResponse'
      security:
        - oauth2: [ ]

  /api/v1/electric-credit/{id}:
    get:
      tags:
        - ElectricCredit
      operationId: getElectricCreditById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Electric Credit details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectricCredit'
      security:
        - oauth2: [ ]
    put:
      tags:
        - ElectricCredit
      operationId: updateElectricCredit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ElectricCreditRequest'
      responses:
        '200':
          description: Updated Electric Credit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ElectricCredit'
      security:
        - oauth2: [ ]
    delete:
      tags:
        - ElectricCredit
      operationId: deleteElectricCredit
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted
      security:
        - oauth2: [ ]

components:
  parameters:
    pageParam:
      name: page
      in: query
      schema:
        type: integer
        default: 0
    sizeParam:
      name: size
      in: query
      schema:
        type: integer
        default: 10

  schemas:
    WeightUnit:
      type: string
      enum:
        - KG
    ElectricOutward:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        challanNo:
          type: string
        weight:
          type: number
          format: double
        perKgWeight:
          type: number
          format: double
        unit:
          type: number
          format: double
        unitRate:
          type: number
          format: double
        totalUnitAmount:
          type: number
          format: double
        totalWeightAmount:
          type: number
          format: double

    ElectricOutwardRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        challanNo:
          type: string
        weight:
          type: number
          format: double
        perKgWeight:
          type: number
          format: double
        unit:
          type: number
          format: double
        unitRate:
          type: number
          format: double

    ElectricCredit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        challanNo:
          type: string
        rate:
          type: number
          format: double

    ElectricCreditRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        challanNo:
          type: string
        rate:
          type: number
          format: double

    PaginatedElectricOutwardResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ElectricOutward'
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        pageNumber:
          type: integer
        pageSize:
          type: integer

    PaginatedElectricCreditResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ElectricCredit'
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        pageNumber:
          type: integer
        pageSize:
          type: integer

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

  securitySchemes:
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: JWT
