openapi: 3.0.3
info:
  title: Subcontracting Management API
  version: 1.0.0
  description: OpenAPI for Subcontracting management
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: http://ec2-65-1-248-131.ap-south-1.compute.amazonaws.com
    description: Production Server

tags:
  - name: Subcontracting
    description: Subcontracting order and return related endpoints
  - name: Subcontract
    description: Subcontract related endpoints

paths:
  /api/v1/subcontracting:
    post:
      tags:
        - Subcontracting
      operationId: addSubcontracting
      summary: Create a new subcontracting order
      description: Adds a new subcontracting record into the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubOrderRequest'
      responses:
        '201':
          description: Subcontracting record successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subcontracting'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
    get:
      tags:
        - Subcontracting
      operationId: getSubcontractingList
      summary: Get all subcontracting orders with pagination
      description: Returns a paginated list of all subcontracting orders.
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/sizeParam'
        - name: status
          in: query
          description: Filter by status
          required: false
          schema:
            type: string
            enum: [ IN_PROCESS, COMPLETED, REJECTED ]
        - name: search
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/SortByFields'
        - $ref: '#/components/parameters/directionParam'
      responses:
        '200':
          description: Paginated list of subcontracting orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResultSubcontract'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
  
  /api/v1/subcontracting/{subcontractingId}:
    put:
      tags:
        - Subcontracting
      operationId: updateSubcontracting
      summary: Update subcontracting order
      description: Updates subcontracting order fields (not return fields).
      parameters:
        - name: subcontractingId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubOrderRequest'
      responses:
        '200':
          description: Subcontracting order successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subcontracting'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Subcontracting order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
    get:
      tags:
        - Subcontracting
      operationId: getSubcontractingById
      summary: Get subcontracting order by ID
      description: Returns a single subcontracting order based on its ID.
      parameters:
        - name: subcontractingId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Subcontracting order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subcontracting'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Subcontracting order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
    delete:
      tags:
        - Subcontracting
      operationId: deleteSubcontracting
      summary: Delete subcontracting order
      description: Deletes a subcontracting order based on its ID.
      parameters:
        - name: subcontractingId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Subcontracting order successfully deleted
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Subcontracting order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
  
  /api/v1/subcontracting/{subcontractingId}/return:
    post:
      tags:
        - Subcontracting
      operationId: returnSubcontracting
      summary: Return Subcontracting Order
      description: Return subcontracting record into the system.
      parameters:
        - name: subcontractingId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubReturnRequest'
      responses:
        '201':
          description: Subcontracting record successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subcontracting'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
  /api/v1/subcontracting/{subcontractingId}/status:
    patch:
      tags:
        - Subcontracting
      operationId: updateSubcontractingStatus
      summary: Update subcontracting order status
      description: Updates only the status of a subcontracting order.
      parameters:
        - name: subcontractingId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  $ref: '#/components/schemas/subcontractingStatus'
      responses:
        '200':
          description: Subcontracting order status successfully updated
        '404':
          description: Subcontracting order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
  /api/v1/subcontracting/getBySubcontract:
    get:
      tags:
        - Subcontract
      operationId: getSubcontractingListBySubcontract
      summary: Get all subcontracting orders By Subcontract
      description: Returns list of all subcontracting orders.
      parameters:
        - name: search
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: list of subcontracting orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubcontractingBySubcontractInfo'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
  /api/v1/subcontracting/getBySubcontract/{contractorName}:
    get:
      tags:
        - Subcontract
      operationId: getSubcontractByCustomerName
      summary: Get Subcontract by customer name
      description: Returns list of all subcontracting orders.
      parameters:
        - name: contractorName
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: list of subcontracting orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubcontractingBySubcontractList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
  /api/v1/subcontracting/getBySubcontract/{contractorName}/pdf:
    get:
      tags:
        - Subcontract
      operationId: getSubcontractByCustomerNamePdf
      summary: Get Subcontract by customer name as pdf
      description: Returns list of all subcontracting orders.
      parameters:
        - name: contractorName
          in: path
          required: true
          schema:
            type: string
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: PDF generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - oauth2: [ ]
components:
  securitySchemes:
    oauth2:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    pageParam:
      name: page
      in: query
      description: Page number starting from 0
      required: false
      schema:
        type: integer
        default: 0

    sizeParam:
      name: size
      in: query
      description: Number of items (records) per page
      required: false
      schema:
        type: integer
        default: 10

    directionParam:
      name: direction
      in: query
      description: Sort direction
      schema:
        type: string
        enum: [ ASC, DESC ]

    SortByFields:
      name: sortByFields
      in: query
      description: Field to sort by
      schema:
        type: string
        enum: [ lastUpdatedAt , createdAt , status , orderDate ]
  schemas:
    SubOrderRequest:
      type: object
      required:
        - contractorName
        - itemName
        - orderDate
        - sentStock
        - jobWorkPay
        - price
        - unit
      properties:
        contractorName:
          type: string
        itemName:
          type: string
        orderDate:
          type: string
          format: date
        sentStock:
          type: number
          format: double
        jobWorkPay:
          type: number
          format: double
        price:
          type: number
          format: double
        unit:
          $ref: "#/components/schemas/unit"
        remark:
          type: string
          nullable: true
    SubReturnRequest:
      type: object
      required:
        - returnItemName
        - returnDate
        - returnStock
        - packagingType
        - returnType
      properties:
        returnItemName:
          type: string
        returnDate:
          type: string
          format: date
        returnStock:
          type: number
          format: double
        returnElement:
          type: number
          format: double
        packagingType:
          $ref: '#/components/schemas/PackagingType'
        returnRemark:
          type: string
          nullable: true

    SubReturn:
      type: object
      properties:
        returnItemName:
          type: string
        returnDate:
          type: string
          format: date
        returnStock:
          type: number
          format: double
        returnElement:
          type: number
          format: double
        packagingType:
          $ref: '#/components/schemas/PackagingType'
        returnRemark:
          type: string
          nullable: true
    Subcontracting:
      type: object
      properties:
        subcontractingId:
          type: integer
        contractorName:
          type: string
        itemName:
          type: string
        orderDate:
          type: string
          format: date
        sentStock:
          type: number
          format: double
        jobWorkPay:
          type: number
          format: double
        price:
          type: number
          format: double
        subReturn:
          $ref: "#/components/schemas/SubReturn"
        usedStock:
          type: number
          format: double
        totalAmount:
          type: number
          format: double
        unit:
          $ref: "#/components/schemas/unit"
        status:
          $ref: "#/components/schemas/subcontractingStatus"
        remark:
          type: string
          nullable: true
    SubcontractingBySubcontractInfo:
      type: object
      properties:
        contractorName:
          type: string
        lastUpdatedAt:
          type: string
          format: date
        itemName:
          type: string
    SubcontractingBySubcontractList:
      type: object
      properties:
        contractorName:
          type: string
        subcontractList:
          type: array
          items:
            $ref: '#/components/schemas/SubcontractingBySubcontract'
        totalPaidRs:
          type: number
          format: double
        totalSentStock:
          type: number
          format: double
        totalReturnStock:
          type: number
          format: double
        totalUsed:
          type: number
          format: double
    SubcontractingBySubcontract:
      type: object
      properties:
        orderDate:
          type: string
          format: date
        price:
          type: number
          format: double
        jobWorkPay:
          type: number
          format: double
        itemName:
          type: string
        sentStock:
          type: number
          format: double
        returnDate:
          type: string
          format: date
        returnItemName:
          type: string
        returnStock:
          type: number
          format: double
        returnElement:
          type: number
          format: double
        packagingType:
          $ref: '#/components/schemas/PackagingType'
        usedStock:
          type: number
          format: double
        netWeight:
          type: number
          format: double
        totalJobPay:
          type: number
          format: double
        totalAmount:
          type: number
          format: double
    subcontractingStatus:
      type: string
      enum:
        - IN_PROCESS
        - COMPLETED
        - REJECTED
    unit:
      type: string
      enum:
        - KG
        - PC
    PackagingType:
      type: string
      enum:
        - BAG
        - FOAM
        - PETI
        - DRUM
    ReturnType:
      type: string
      enum:
        - MAAL
        - CHHOL
        - TAYAR_MAAL
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
        detail:
          type: object
          additionalProperties: true
    PaginatedResultSubcontract:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Subcontracting'
        empty:
          type: boolean
          description: Indicates if the current page is empty
        last:
          type: boolean
          description: Indicates if the current page is the last page
        first:
          type: boolean
          description: Indicates if the current page is the first page
        totalPages:
          type: integer
          description: Total number of pages available
        totalElements:
          type: integer
          description: Total number of elements
        size:
          type: integer
          description: Number of items per page