/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import Party from '../model/Party';
import PartyRequest from '../model/PartyRequest';

/**
* Party service.
* @module api/PartyApi
* @version 1.0.0
*/
export default class PartyApi {

    /**
    * Constructs a new PartyApi. 
    * @alias module:api/PartyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addParty operation.
     * @callback module:api/PartyApi~addPartyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Party} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Party
     * @param {module:model/PartyRequest} partyRequest 
     * @param {module:api/PartyApi~addPartyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Party}
     */
    addParty(partyRequest, callback) {
      let postBody = partyRequest;
      // verify the required parameter 'partyRequest' is set
      if (partyRequest === undefined || partyRequest === null) {
        throw new Error("Missing the required parameter 'partyRequest' when calling addParty");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Party;
      return this.apiClient.callApi(
        '/api/v1/party', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPartyById operation.
     * @callback module:api/PartyApi~getPartyByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Party} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get party by ID
     * @param {Number} partyId 
     * @param {module:api/PartyApi~getPartyByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Party}
     */
    getPartyById(partyId, callback) {
      let postBody = null;
      // verify the required parameter 'partyId' is set
      if (partyId === undefined || partyId === null) {
        throw new Error("Missing the required parameter 'partyId' when calling getPartyById");
      }

      let pathParams = {
        'partyId': partyId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Party;
      return this.apiClient.callApi(
        '/api/v1/party/{partyId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPartyList operation.
     * @callback module:api/PartyApi~getPartyListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Party>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all parties
     * @param {module:api/PartyApi~getPartyListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Party>}
     */
    getPartyList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Party];
      return this.apiClient.callApi(
        '/api/v1/party', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
