/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import PaginatedResultSubcontract from '../model/PaginatedResultSubcontract';
import SubOrderRequest from '../model/SubOrderRequest';
import SubReturnRequest from '../model/SubReturnRequest';
import Subcontracting from '../model/Subcontracting';
import UpdateSubcontractingStatusRequest from '../model/UpdateSubcontractingStatusRequest';

/**
* Subcontracting service.
* @module api/SubcontractingApi
* @version 1.0.0
*/
export default class SubcontractingApi {

    /**
    * Constructs a new SubcontractingApi. 
    * @alias module:api/SubcontractingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addSubcontracting operation.
     * @callback module:api/SubcontractingApi~addSubcontractingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subcontracting} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new subcontracting order
     * Adds a new subcontracting record into the system.
     * @param {module:model/SubOrderRequest} subOrderRequest 
     * @param {module:api/SubcontractingApi~addSubcontractingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Subcontracting}
     */
    addSubcontracting(subOrderRequest, callback) {
      let postBody = subOrderRequest;
      // verify the required parameter 'subOrderRequest' is set
      if (subOrderRequest === undefined || subOrderRequest === null) {
        throw new Error("Missing the required parameter 'subOrderRequest' when calling addSubcontracting");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Subcontracting;
      return this.apiClient.callApi(
        '/api/v1/subcontracting', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteSubcontracting operation.
     * @callback module:api/SubcontractingApi~deleteSubcontractingCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete subcontracting order
     * Deletes a subcontracting order based on its ID.
     * @param {Number} subcontractingId 
     * @param {module:api/SubcontractingApi~deleteSubcontractingCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteSubcontracting(subcontractingId, callback) {
      let postBody = null;
      // verify the required parameter 'subcontractingId' is set
      if (subcontractingId === undefined || subcontractingId === null) {
        throw new Error("Missing the required parameter 'subcontractingId' when calling deleteSubcontracting");
      }

      let pathParams = {
        'subcontractingId': subcontractingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/{subcontractingId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubcontractingById operation.
     * @callback module:api/SubcontractingApi~getSubcontractingByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subcontracting} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get subcontracting order by ID
     * Returns a single subcontracting order based on its ID.
     * @param {Number} subcontractingId 
     * @param {module:api/SubcontractingApi~getSubcontractingByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Subcontracting}
     */
    getSubcontractingById(subcontractingId, callback) {
      let postBody = null;
      // verify the required parameter 'subcontractingId' is set
      if (subcontractingId === undefined || subcontractingId === null) {
        throw new Error("Missing the required parameter 'subcontractingId' when calling getSubcontractingById");
      }

      let pathParams = {
        'subcontractingId': subcontractingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Subcontracting;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/{subcontractingId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubcontractingList operation.
     * @callback module:api/SubcontractingApi~getSubcontractingListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResultSubcontract} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all subcontracting orders with pagination
     * Returns a paginated list of all subcontracting orders.
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page number starting from 0
     * @param {Number} [size = 10)] Number of items (records) per page
     * @param {module:model/String} [status] Filter by status
     * @param {String} [search] 
     * @param {module:model/String} [sortByFields] Field to sort by
     * @param {module:model/String} [direction] Sort direction
     * @param {module:api/SubcontractingApi~getSubcontractingListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResultSubcontract}
     */
    getSubcontractingList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'status': opts['status'],
        'search': opts['search'],
        'sortByFields': opts['sortByFields'],
        'direction': opts['direction']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedResultSubcontract;
      return this.apiClient.callApi(
        '/api/v1/subcontracting', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the returnSubcontracting operation.
     * @callback module:api/SubcontractingApi~returnSubcontractingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subcontracting} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return Subcontracting Order
     * Return subcontracting record into the system.
     * @param {Number} subcontractingId 
     * @param {module:model/SubReturnRequest} subReturnRequest 
     * @param {module:api/SubcontractingApi~returnSubcontractingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Subcontracting}
     */
    returnSubcontracting(subcontractingId, subReturnRequest, callback) {
      let postBody = subReturnRequest;
      // verify the required parameter 'subcontractingId' is set
      if (subcontractingId === undefined || subcontractingId === null) {
        throw new Error("Missing the required parameter 'subcontractingId' when calling returnSubcontracting");
      }
      // verify the required parameter 'subReturnRequest' is set
      if (subReturnRequest === undefined || subReturnRequest === null) {
        throw new Error("Missing the required parameter 'subReturnRequest' when calling returnSubcontracting");
      }

      let pathParams = {
        'subcontractingId': subcontractingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Subcontracting;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/{subcontractingId}/return', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSubcontracting operation.
     * @callback module:api/SubcontractingApi~updateSubcontractingCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subcontracting} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update subcontracting order
     * Updates subcontracting order fields (not return fields).
     * @param {Number} subcontractingId 
     * @param {module:model/SubOrderRequest} subOrderRequest 
     * @param {module:api/SubcontractingApi~updateSubcontractingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Subcontracting}
     */
    updateSubcontracting(subcontractingId, subOrderRequest, callback) {
      let postBody = subOrderRequest;
      // verify the required parameter 'subcontractingId' is set
      if (subcontractingId === undefined || subcontractingId === null) {
        throw new Error("Missing the required parameter 'subcontractingId' when calling updateSubcontracting");
      }
      // verify the required parameter 'subOrderRequest' is set
      if (subOrderRequest === undefined || subOrderRequest === null) {
        throw new Error("Missing the required parameter 'subOrderRequest' when calling updateSubcontracting");
      }

      let pathParams = {
        'subcontractingId': subcontractingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Subcontracting;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/{subcontractingId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateSubcontractingStatus operation.
     * @callback module:api/SubcontractingApi~updateSubcontractingStatusCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update subcontracting order status
     * Updates only the status of a subcontracting order.
     * @param {Number} subcontractingId 
     * @param {module:model/UpdateSubcontractingStatusRequest} updateSubcontractingStatusRequest 
     * @param {module:api/SubcontractingApi~updateSubcontractingStatusCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateSubcontractingStatus(subcontractingId, updateSubcontractingStatusRequest, callback) {
      let postBody = updateSubcontractingStatusRequest;
      // verify the required parameter 'subcontractingId' is set
      if (subcontractingId === undefined || subcontractingId === null) {
        throw new Error("Missing the required parameter 'subcontractingId' when calling updateSubcontractingStatus");
      }
      // verify the required parameter 'updateSubcontractingStatusRequest' is set
      if (updateSubcontractingStatusRequest === undefined || updateSubcontractingStatusRequest === null) {
        throw new Error("Missing the required parameter 'updateSubcontractingStatusRequest' when calling updateSubcontractingStatus");
      }

      let pathParams = {
        'subcontractingId': subcontractingId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/{subcontractingId}/status', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
