/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import SubcontractingBySubcontractInfo from '../model/SubcontractingBySubcontractInfo';
import SubcontractingBySubcontractList from '../model/SubcontractingBySubcontractList';

/**
* Subcontract service.
* @module api/SubcontractApi
* @version 1.0.0
*/
export default class SubcontractApi {

    /**
    * Constructs a new SubcontractApi. 
    * @alias module:api/SubcontractApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getSubcontractByCustomerName operation.
     * @callback module:api/SubcontractApi~getSubcontractByCustomerNameCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SubcontractingBySubcontractList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Subcontract by customer name
     * Returns list of all subcontracting orders.
     * @param {String} contractorName 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @param {module:api/SubcontractApi~getSubcontractByCustomerNameCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SubcontractingBySubcontractList}
     */
    getSubcontractByCustomerName(contractorName, startDate, endDate, callback) {
      let postBody = null;
      // verify the required parameter 'contractorName' is set
      if (contractorName === undefined || contractorName === null) {
        throw new Error("Missing the required parameter 'contractorName' when calling getSubcontractByCustomerName");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getSubcontractByCustomerName");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getSubcontractByCustomerName");
      }

      let pathParams = {
        'contractorName': contractorName
      };
      let queryParams = {
        'startDate': startDate,
        'endDate': endDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SubcontractingBySubcontractList;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/getBySubcontract/{contractorName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubcontractByCustomerNamePdf operation.
     * @callback module:api/SubcontractApi~getSubcontractByCustomerNamePdfCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Subcontract by customer name as pdf
     * Returns list of all subcontracting orders.
     * @param {String} contractorName 
     * @param {Date} startDate 
     * @param {Date} endDate 
     * @param {module:api/SubcontractApi~getSubcontractByCustomerNamePdfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    getSubcontractByCustomerNamePdf(contractorName, startDate, endDate, callback) {
      let postBody = null;
      // verify the required parameter 'contractorName' is set
      if (contractorName === undefined || contractorName === null) {
        throw new Error("Missing the required parameter 'contractorName' when calling getSubcontractByCustomerNamePdf");
      }
      // verify the required parameter 'startDate' is set
      if (startDate === undefined || startDate === null) {
        throw new Error("Missing the required parameter 'startDate' when calling getSubcontractByCustomerNamePdf");
      }
      // verify the required parameter 'endDate' is set
      if (endDate === undefined || endDate === null) {
        throw new Error("Missing the required parameter 'endDate' when calling getSubcontractByCustomerNamePdf");
      }

      let pathParams = {
        'contractorName': contractorName
      };
      let queryParams = {
        'startDate': startDate,
        'endDate': endDate
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/pdf', 'application/json'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/subcontracting/getBySubcontract/{contractorName}/pdf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getSubcontractingListBySubcontract operation.
     * @callback module:api/SubcontractApi~getSubcontractingListBySubcontractCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SubcontractingBySubcontractInfo>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all subcontracting orders By Subcontract
     * Returns list of all subcontracting orders.
     * @param {Object} opts Optional parameters
     * @param {String} [search] 
     * @param {module:api/SubcontractApi~getSubcontractingListBySubcontractCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SubcontractingBySubcontractInfo>}
     */
    getSubcontractingListBySubcontract(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SubcontractingBySubcontractInfo];
      return this.apiClient.callApi(
        '/api/v1/subcontracting/getBySubcontract', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
