/**
 * Casting API
 * OpenAPI for Casting Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CastingSale from '../model/CastingSale';
import CastingSaleRequest from '../model/CastingSaleRequest';
import PaginatedCastingSaleResponse from '../model/PaginatedCastingSaleResponse';

/**
* CastingSale service.
* @module api/CastingSaleApi
* @version 1.0.0
*/
export default class CastingSaleApi {

    /**
    * Constructs a new CastingSaleApi. 
    * @alias module:api/CastingSaleApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createCastingSale operation.
     * @callback module:api/CastingSaleApi~createCastingSaleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CastingSale} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Casting Sale
     * @param {module:model/CastingSaleRequest} castingSaleRequest 
     * @param {module:api/CastingSaleApi~createCastingSaleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CastingSale}
     */
    createCastingSale(castingSaleRequest, callback) {
      let postBody = castingSaleRequest;
      // verify the required parameter 'castingSaleRequest' is set
      if (castingSaleRequest === undefined || castingSaleRequest === null) {
        throw new Error("Missing the required parameter 'castingSaleRequest' when calling createCastingSale");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CastingSale;
      return this.apiClient.callApi(
        '/api/v1/casting-sale', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteCastingSale operation.
     * @callback module:api/CastingSaleApi~deleteCastingSaleCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/CastingSaleApi~deleteCastingSaleCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteCastingSale(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteCastingSale");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/casting-sale/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the downloadCastingSalePdf operation.
     * @callback module:api/CastingSaleApi~downloadCastingSalePdfCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Download Casting Sale Statement PDF
     * Generates a statement-style PDF of all casting sale records with optional date range filtering
     * @param {Object} opts Optional parameters
     * @param {Date} [fromDate] 
     * @param {Date} [toDate] 
     * @param {module:api/CastingSaleApi~downloadCastingSalePdfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    downloadCastingSalePdf(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'fromDate': opts['fromDate'],
        'toDate': opts['toDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/casting-sale/pdf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCastingSaleById operation.
     * @callback module:api/CastingSaleApi~getCastingSaleByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CastingSale} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:api/CastingSaleApi~getCastingSaleByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CastingSale}
     */
    getCastingSaleById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCastingSaleById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CastingSale;
      return this.apiClient.callApi(
        '/api/v1/casting-sale/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchCastingSales operation.
     * @callback module:api/CastingSaleApi~searchCastingSalesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedCastingSaleResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 10)] 
     * @param {module:api/CastingSaleApi~searchCastingSalesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedCastingSaleResponse}
     */
    searchCastingSales(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedCastingSaleResponse;
      return this.apiClient.callApi(
        '/api/v1/casting-sale', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCastingSale operation.
     * @callback module:api/CastingSaleApi~updateCastingSaleCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CastingSale} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} id 
     * @param {module:model/CastingSaleRequest} castingSaleRequest 
     * @param {module:api/CastingSaleApi~updateCastingSaleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CastingSale}
     */
    updateCastingSale(id, castingSaleRequest, callback) {
      let postBody = castingSaleRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateCastingSale");
      }
      // verify the required parameter 'castingSaleRequest' is set
      if (castingSaleRequest === undefined || castingSaleRequest === null) {
        throw new Error("Missing the required parameter 'castingSaleRequest' when calling updateCastingSale");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CastingSale;
      return this.apiClient.callApi(
        '/api/v1/casting-sale/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
