/**
 * Casting API
 * OpenAPI for Casting Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CastingSale model module.
 * @module model/CastingSale
 * @version 1.0.0
 */
class CastingSale {
    /**
     * Constructs a new <code>CastingSale</code>.
     * @alias module:model/CastingSale
     */
    constructor() { 
        
        CastingSale.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CastingSale</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CastingSale} obj Optional instance to populate.
     * @return {module:model/CastingSale} The populated <code>CastingSale</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CastingSale();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('brassWeight')) {
                obj['brassWeight'] = ApiClient.convertToType(data['brassWeight'], 'Number');
            }
            if (data.hasOwnProperty('kadiWeight')) {
                obj['kadiWeight'] = ApiClient.convertToType(data['kadiWeight'], 'Number');
            }
            if (data.hasOwnProperty('kadiRate')) {
                obj['kadiRate'] = ApiClient.convertToType(data['kadiRate'], 'Number');
            }
            if (data.hasOwnProperty('kadiAmount')) {
                obj['kadiAmount'] = ApiClient.convertToType(data['kadiAmount'], 'Number');
            }
            if (data.hasOwnProperty('lokhandWeight')) {
                obj['lokhandWeight'] = ApiClient.convertToType(data['lokhandWeight'], 'Number');
            }
            if (data.hasOwnProperty('lokhandRate')) {
                obj['lokhandRate'] = ApiClient.convertToType(data['lokhandRate'], 'Number');
            }
            if (data.hasOwnProperty('lokhandAmount')) {
                obj['lokhandAmount'] = ApiClient.convertToType(data['lokhandAmount'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CastingSale</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CastingSale</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} id
 */
CastingSale.prototype['id'] = undefined;

/**
 * @member {Date} date
 */
CastingSale.prototype['date'] = undefined;

/**
 * @member {Number} brassWeight
 */
CastingSale.prototype['brassWeight'] = undefined;

/**
 * @member {Number} kadiWeight
 */
CastingSale.prototype['kadiWeight'] = undefined;

/**
 * @member {Number} kadiRate
 */
CastingSale.prototype['kadiRate'] = undefined;

/**
 * @member {Number} kadiAmount
 */
CastingSale.prototype['kadiAmount'] = undefined;

/**
 * @member {Number} lokhandWeight
 */
CastingSale.prototype['lokhandWeight'] = undefined;

/**
 * @member {Number} lokhandRate
 */
CastingSale.prototype['lokhandRate'] = undefined;

/**
 * @member {Number} lokhandAmount
 */
CastingSale.prototype['lokhandAmount'] = undefined;

/**
 * @member {Number} totalAmount
 */
CastingSale.prototype['totalAmount'] = undefined;






export default CastingSale;

