/**
 * Casting API
 * OpenAPI for Casting Management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Casting from './Casting';

/**
 * The PaginatedCastingResponse model module.
 * @module model/PaginatedCastingResponse
 * @version 1.0.0
 */
class PaginatedCastingResponse {
    /**
     * Constructs a new <code>PaginatedCastingResponse</code>.
     * @alias module:model/PaginatedCastingResponse
     */
    constructor() { 
        
        PaginatedCastingResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginatedCastingResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedCastingResponse} obj Optional instance to populate.
     * @return {module:model/PaginatedCastingResponse} The populated <code>PaginatedCastingResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedCastingResponse();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [Casting]);
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
            if (data.hasOwnProperty('pageSize')) {
                obj['pageSize'] = ApiClient.convertToType(data['pageSize'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaginatedCastingResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaginatedCastingResponse</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                Casting.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Casting>} content
 */
PaginatedCastingResponse.prototype['content'] = undefined;

/**
 * @member {Number} totalElements
 */
PaginatedCastingResponse.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
PaginatedCastingResponse.prototype['totalPages'] = undefined;

/**
 * @member {Number} pageNumber
 */
PaginatedCastingResponse.prototype['pageNumber'] = undefined;

/**
 * @member {Number} pageSize
 */
PaginatedCastingResponse.prototype['pageSize'] = undefined;






export default PaginatedCastingResponse;

