/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import JayeshScrap from '../model/JayeshScrap';
import JayeshScrapRequest from '../model/JayeshScrapRequest';
import JayeshScrapWithdrawRequest from '../model/JayeshScrapWithdrawRequest';
import PaginatedResultJayeshScrap from '../model/PaginatedResultJayeshScrap';

/**
* JayeshScrap service.
* @module api/JayeshScrapApi
* @version 1.0.0
*/
export default class JayeshScrapApi {

    /**
    * Constructs a new JayeshScrapApi. 
    * @alias module:api/JayeshScrapApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addJayeshScrap operation.
     * @callback module:api/JayeshScrapApi~addJayeshScrapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JayeshScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new Jayesh scrap entry
     * @param {module:model/JayeshScrapRequest} jayeshScrapRequest 
     * @param {module:api/JayeshScrapApi~addJayeshScrapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JayeshScrap}
     */
    addJayeshScrap(jayeshScrapRequest, callback) {
      let postBody = jayeshScrapRequest;
      // verify the required parameter 'jayeshScrapRequest' is set
      if (jayeshScrapRequest === undefined || jayeshScrapRequest === null) {
        throw new Error("Missing the required parameter 'jayeshScrapRequest' when calling addJayeshScrap");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = JayeshScrap;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteJayeshScrap operation.
     * @callback module:api/JayeshScrapApi~deleteJayeshScrapCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Jayesh scrap entry
     * @param {Number} scrapId 
     * @param {module:api/JayeshScrapApi~deleteJayeshScrapCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteJayeshScrap(scrapId, callback) {
      let postBody = null;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling deleteJayeshScrap");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap/{scrapId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the exportJayeshScrapPdf operation.
     * @callback module:api/JayeshScrapApi~exportJayeshScrapPdfCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Export Jayesh Scrap records to PDF
     * @param {Object} opts Optional parameters
     * @param {Date} [fromDate] 
     * @param {Date} [toDate] 
     * @param {module:api/JayeshScrapApi~exportJayeshScrapPdfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    exportJayeshScrapPdf(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'fromDate': opts['fromDate'],
        'toDate': opts['toDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap/export/pdf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getJayeshScrapById operation.
     * @callback module:api/JayeshScrapApi~getJayeshScrapByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JayeshScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Jayesh scrap entry by ID
     * @param {Number} scrapId 
     * @param {module:api/JayeshScrapApi~getJayeshScrapByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JayeshScrap}
     */
    getJayeshScrapById(scrapId, callback) {
      let postBody = null;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling getJayeshScrapById");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = JayeshScrap;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap/{scrapId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getJayeshScrapList operation.
     * @callback module:api/JayeshScrapApi~getJayeshScrapListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResultJayeshScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Jayesh scrap entries with pagination
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page number starting from 0
     * @param {Number} [size = 10)] Number of items (records) per page
     * @param {String} [search] 
     * @param {module:model/String} [sortByFields] Field to sort by
     * @param {module:model/String} [direction] Sort direction
     * @param {module:api/JayeshScrapApi~getJayeshScrapListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResultJayeshScrap}
     */
    getJayeshScrapList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'search': opts['search'],
        'sortByFields': opts['sortByFields'],
        'direction': opts['direction']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedResultJayeshScrap;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getJayeshScrapItems operation.
     * @callback module:api/JayeshScrapApi~getJayeshScrapItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get distinct item names from Jayesh scrap entries
     * @param {module:api/JayeshScrapApi~getJayeshScrapItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getJayeshScrapItems(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap/items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateJayeshScrap operation.
     * @callback module:api/JayeshScrapApi~updateJayeshScrapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JayeshScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Jayesh scrap entry
     * @param {Number} scrapId 
     * @param {module:model/JayeshScrapRequest} jayeshScrapRequest 
     * @param {module:api/JayeshScrapApi~updateJayeshScrapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JayeshScrap}
     */
    updateJayeshScrap(scrapId, jayeshScrapRequest, callback) {
      let postBody = jayeshScrapRequest;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling updateJayeshScrap");
      }
      // verify the required parameter 'jayeshScrapRequest' is set
      if (jayeshScrapRequest === undefined || jayeshScrapRequest === null) {
        throw new Error("Missing the required parameter 'jayeshScrapRequest' when calling updateJayeshScrap");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = JayeshScrap;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap/{scrapId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the withdrawJayeshScrap operation.
     * @callback module:api/JayeshScrapApi~withdrawJayeshScrapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JayeshScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Record a withdrawal amount and calculate pending amount (totalAmount - withdrawAmount)
     * @param {Number} scrapId 
     * @param {module:model/JayeshScrapWithdrawRequest} jayeshScrapWithdrawRequest 
     * @param {module:api/JayeshScrapApi~withdrawJayeshScrapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JayeshScrap}
     */
    withdrawJayeshScrap(scrapId, jayeshScrapWithdrawRequest, callback) {
      let postBody = jayeshScrapWithdrawRequest;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling withdrawJayeshScrap");
      }
      // verify the required parameter 'jayeshScrapWithdrawRequest' is set
      if (jayeshScrapWithdrawRequest === undefined || jayeshScrapWithdrawRequest === null) {
        throw new Error("Missing the required parameter 'jayeshScrapWithdrawRequest' when calling withdrawJayeshScrap");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = JayeshScrap;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap/{scrapId}/withdraw', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
