/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import JayeshScrapContractor from '../model/JayeshScrapContractor';
import JayeshScrapContractorRequest from '../model/JayeshScrapContractorRequest';

/**
* JayeshScrapContractor service.
* @module api/JayeshScrapContractorApi
* @version 1.0.0
*/
export default class JayeshScrapContractorApi {

    /**
    * Constructs a new JayeshScrapContractorApi. 
    * @alias module:api/JayeshScrapContractorApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addJayeshScrapContractor operation.
     * @callback module:api/JayeshScrapContractorApi~addJayeshScrapContractorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JayeshScrapContractor} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Jayesh Scrap Contractor
     * Adds a new scrap contractor for Jayesh.
     * @param {module:model/JayeshScrapContractorRequest} jayeshScrapContractorRequest 
     * @param {module:api/JayeshScrapContractorApi~addJayeshScrapContractorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JayeshScrapContractor}
     */
    addJayeshScrapContractor(jayeshScrapContractorRequest, callback) {
      let postBody = jayeshScrapContractorRequest;
      // verify the required parameter 'jayeshScrapContractorRequest' is set
      if (jayeshScrapContractorRequest === undefined || jayeshScrapContractorRequest === null) {
        throw new Error("Missing the required parameter 'jayeshScrapContractorRequest' when calling addJayeshScrapContractor");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = JayeshScrapContractor;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap-contractor', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getJayeshScrapContractorById operation.
     * @callback module:api/JayeshScrapContractorApi~getJayeshScrapContractorByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/JayeshScrapContractor} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Jayesh scrap contractor by ID
     * @param {Number} scrapContractorId 
     * @param {module:api/JayeshScrapContractorApi~getJayeshScrapContractorByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/JayeshScrapContractor}
     */
    getJayeshScrapContractorById(scrapContractorId, callback) {
      let postBody = null;
      // verify the required parameter 'scrapContractorId' is set
      if (scrapContractorId === undefined || scrapContractorId === null) {
        throw new Error("Missing the required parameter 'scrapContractorId' when calling getJayeshScrapContractorById");
      }

      let pathParams = {
        'scrapContractorId': scrapContractorId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = JayeshScrapContractor;
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap-contractor/{scrapContractorId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getJayeshScrapContractorList operation.
     * @callback module:api/JayeshScrapContractorApi~getJayeshScrapContractorListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/JayeshScrapContractor>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Jayesh scrap contractors
     * @param {module:api/JayeshScrapContractorApi~getJayeshScrapContractorListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/JayeshScrapContractor>}
     */
    getJayeshScrapContractorList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [JayeshScrapContractor];
      return this.apiClient.callApi(
        '/api/v1/jayesh/scrap-contractor', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
