/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import KevinScrapContractor from '../model/KevinScrapContractor';
import KevinScrapContractorRequest from '../model/KevinScrapContractorRequest';

/**
* KevinScrapContractor service.
* @module api/KevinScrapContractorApi
* @version 1.0.0
*/
export default class KevinScrapContractorApi {

    /**
    * Constructs a new KevinScrapContractorApi. 
    * @alias module:api/KevinScrapContractorApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addKevinScrapContractor operation.
     * @callback module:api/KevinScrapContractorApi~addKevinScrapContractorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KevinScrapContractor} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add Kevin Scrap Contractor
     * Adds a new scrap contractor for Kevin.
     * @param {module:model/KevinScrapContractorRequest} kevinScrapContractorRequest 
     * @param {module:api/KevinScrapContractorApi~addKevinScrapContractorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KevinScrapContractor}
     */
    addKevinScrapContractor(kevinScrapContractorRequest, callback) {
      let postBody = kevinScrapContractorRequest;
      // verify the required parameter 'kevinScrapContractorRequest' is set
      if (kevinScrapContractorRequest === undefined || kevinScrapContractorRequest === null) {
        throw new Error("Missing the required parameter 'kevinScrapContractorRequest' when calling addKevinScrapContractor");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = KevinScrapContractor;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap-contractor', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getKevinScrapContractorById operation.
     * @callback module:api/KevinScrapContractorApi~getKevinScrapContractorByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KevinScrapContractor} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Kevin scrap contractor by ID
     * @param {Number} scrapContractorId 
     * @param {module:api/KevinScrapContractorApi~getKevinScrapContractorByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KevinScrapContractor}
     */
    getKevinScrapContractorById(scrapContractorId, callback) {
      let postBody = null;
      // verify the required parameter 'scrapContractorId' is set
      if (scrapContractorId === undefined || scrapContractorId === null) {
        throw new Error("Missing the required parameter 'scrapContractorId' when calling getKevinScrapContractorById");
      }

      let pathParams = {
        'scrapContractorId': scrapContractorId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = KevinScrapContractor;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap-contractor/{scrapContractorId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getKevinScrapContractorList operation.
     * @callback module:api/KevinScrapContractorApi~getKevinScrapContractorListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/KevinScrapContractor>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Kevin scrap contractors
     * @param {module:api/KevinScrapContractorApi~getKevinScrapContractorListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/KevinScrapContractor>}
     */
    getKevinScrapContractorList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [KevinScrapContractor];
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap-contractor', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
