/**
 * Scrap Management API
 * OpenAPI for Scrap management - Kevin and Jayesh dashboards
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import KevinScrap from '../model/KevinScrap';
import KevinScrapRequest from '../model/KevinScrapRequest';
import PaginatedResultKevinScrap from '../model/PaginatedResultKevinScrap';

/**
* KevinScrap service.
* @module api/KevinScrapApi
* @version 1.0.0
*/
export default class KevinScrapApi {

    /**
    * Constructs a new KevinScrapApi. 
    * @alias module:api/KevinScrapApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addKevinScrap operation.
     * @callback module:api/KevinScrapApi~addKevinScrapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KevinScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new Kevin scrap entry
     * @param {module:model/KevinScrapRequest} kevinScrapRequest 
     * @param {module:api/KevinScrapApi~addKevinScrapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KevinScrap}
     */
    addKevinScrap(kevinScrapRequest, callback) {
      let postBody = kevinScrapRequest;
      // verify the required parameter 'kevinScrapRequest' is set
      if (kevinScrapRequest === undefined || kevinScrapRequest === null) {
        throw new Error("Missing the required parameter 'kevinScrapRequest' when calling addKevinScrap");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = KevinScrap;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteKevinScrap operation.
     * @callback module:api/KevinScrapApi~deleteKevinScrapCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Kevin scrap entry
     * @param {Number} scrapId 
     * @param {module:api/KevinScrapApi~deleteKevinScrapCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteKevinScrap(scrapId, callback) {
      let postBody = null;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling deleteKevinScrap");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap/{scrapId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the exportKevinScrapPdf operation.
     * @callback module:api/KevinScrapApi~exportKevinScrapPdfCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Export Kevin Scrap records to PDF
     * @param {Object} opts Optional parameters
     * @param {Date} [fromDate] 
     * @param {Date} [toDate] 
     * @param {module:api/KevinScrapApi~exportKevinScrapPdfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    exportKevinScrapPdf(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'fromDate': opts['fromDate'],
        'toDate': opts['toDate']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/pdf'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap/export/pdf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getKevinScrapById operation.
     * @callback module:api/KevinScrapApi~getKevinScrapByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KevinScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Kevin scrap entry by ID
     * @param {Number} scrapId 
     * @param {module:api/KevinScrapApi~getKevinScrapByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KevinScrap}
     */
    getKevinScrapById(scrapId, callback) {
      let postBody = null;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling getKevinScrapById");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = KevinScrap;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap/{scrapId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getKevinScrapList operation.
     * @callback module:api/KevinScrapApi~getKevinScrapListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResultKevinScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all Kevin scrap entries with pagination
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page number starting from 0
     * @param {Number} [size = 10)] Number of items (records) per page
     * @param {String} [search] 
     * @param {module:model/String} [sortByFields] Field to sort by
     * @param {module:model/String} [direction] Sort direction
     * @param {module:api/KevinScrapApi~getKevinScrapListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResultKevinScrap}
     */
    getKevinScrapList(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'search': opts['search'],
        'sortByFields': opts['sortByFields'],
        'direction': opts['direction']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedResultKevinScrap;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getKevinScrapItems operation.
     * @callback module:api/KevinScrapApi~getKevinScrapItemsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get distinct item names from Kevin scrap entries
     * @param {module:api/KevinScrapApi~getKevinScrapItemsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    getKevinScrapItems(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap/items', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateKevinScrap operation.
     * @callback module:api/KevinScrapApi~updateKevinScrapCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KevinScrap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Kevin scrap entry
     * @param {Number} scrapId 
     * @param {module:model/KevinScrapRequest} kevinScrapRequest 
     * @param {module:api/KevinScrapApi~updateKevinScrapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KevinScrap}
     */
    updateKevinScrap(scrapId, kevinScrapRequest, callback) {
      let postBody = kevinScrapRequest;
      // verify the required parameter 'scrapId' is set
      if (scrapId === undefined || scrapId === null) {
        throw new Error("Missing the required parameter 'scrapId' when calling updateKevinScrap");
      }
      // verify the required parameter 'kevinScrapRequest' is set
      if (kevinScrapRequest === undefined || kevinScrapRequest === null) {
        throw new Error("Missing the required parameter 'kevinScrapRequest' when calling updateKevinScrap");
      }

      let pathParams = {
        'scrapId': scrapId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = KevinScrap;
      return this.apiClient.callApi(
        '/api/v1/kevin/scrap/{scrapId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
