/**
 * Image Management API
 * OpenAPI for image upload and management using Cloudinary
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ImageResponse model module.
 * @module model/ImageResponse
 * @version 1.0.0
 */
class ImageResponse {
    /**
     * Constructs a new <code>ImageResponse</code>.
     * @alias module:model/ImageResponse
     */
    constructor() { 
        
        ImageResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ImageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ImageResponse} obj Optional instance to populate.
     * @return {module:model/ImageResponse} The populated <code>ImageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageResponse();

            if (data.hasOwnProperty('imageName')) {
                obj['imageName'] = ApiClient.convertToType(data['imageName'], 'String');
            }
            if (data.hasOwnProperty('imageLocation')) {
                obj['imageLocation'] = ApiClient.convertToType(data['imageLocation'], 'String');
            }
            if (data.hasOwnProperty('publicId')) {
                obj['publicId'] = ApiClient.convertToType(data['publicId'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ImageResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ImageResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['imageName'] && !(typeof data['imageName'] === 'string' || data['imageName'] instanceof String)) {
            throw new Error("Expected the field `imageName` to be a primitive type in the JSON string but got " + data['imageName']);
        }
        // ensure the json data is a string
        if (data['imageLocation'] && !(typeof data['imageLocation'] === 'string' || data['imageLocation'] instanceof String)) {
            throw new Error("Expected the field `imageLocation` to be a primitive type in the JSON string but got " + data['imageLocation']);
        }
        // ensure the json data is a string
        if (data['publicId'] && !(typeof data['publicId'] === 'string' || data['publicId'] instanceof String)) {
            throw new Error("Expected the field `publicId` to be a primitive type in the JSON string but got " + data['publicId']);
        }
        // ensure the json data is a string
        if (data['format'] && !(typeof data['format'] === 'string' || data['format'] instanceof String)) {
            throw new Error("Expected the field `format` to be a primitive type in the JSON string but got " + data['format']);
        }

        return true;
    }


}



/**
 * Original name of the uploaded image
 * @member {String} imageName
 */
ImageResponse.prototype['imageName'] = undefined;

/**
 * Secure URL of the uploaded image
 * @member {String} imageLocation
 */
ImageResponse.prototype['imageLocation'] = undefined;

/**
 * Public ID of the uploaded image in Cloudinary
 * @member {String} publicId
 */
ImageResponse.prototype['publicId'] = undefined;

/**
 * Format of the uploaded image
 * @member {String} format
 */
ImageResponse.prototype['format'] = undefined;

/**
 * Width of the uploaded image in pixels
 * @member {Number} width
 */
ImageResponse.prototype['width'] = undefined;

/**
 * Height of the uploaded image in pixels
 * @member {Number} height
 */
ImageResponse.prototype['height'] = undefined;






export default ImageResponse;

