/**
 * Order Management API
 * OpenAPI for order management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DispatchRequest from '../model/DispatchRequest';
import ErrorResponse from '../model/ErrorResponse';
import Order from '../model/Order';
import OrderFloor from '../model/OrderFloor';
import OrderRequest from '../model/OrderRequest';
import PaginatedResultOrder from '../model/PaginatedResultOrder';
import UpdateOrderStatusRequest from '../model/UpdateOrderStatusRequest';

/**
* Orders service.
* @module api/OrdersApi
* @version 1.0.0
*/
export default class OrdersApi {

    /**
    * Constructs a new OrdersApi. 
    * @alias module:api/OrdersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createOrder operation.
     * @callback module:api/OrdersApi~createOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new order (with products & billing details)
     * @param {module:model/OrderRequest} orderRequest 
     * @param {module:api/OrdersApi~createOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    createOrder(orderRequest, callback) {
      let postBody = orderRequest;
      // verify the required parameter 'orderRequest' is set
      if (orderRequest === undefined || orderRequest === null) {
        throw new Error("Missing the required parameter 'orderRequest' when calling createOrder");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/api/v1/orders', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteOrder operation.
     * @callback module:api/OrdersApi~deleteOrderCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an order and all associated products.
     * @param {Number} orderId 
     * @param {module:api/OrdersApi~deleteOrderCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteOrder(orderId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling deleteOrder");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/orders/{orderId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the dispatchOrder operation.
     * @callback module:api/OrdersApi~dispatchOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Dispatch order and deduct quantities from inventory
     * Deducts specified quantities from stock inventory for each item and marks the order as DISPATCHED
     * @param {Number} orderId 
     * @param {module:model/DispatchRequest} dispatchRequest 
     * @param {module:api/OrdersApi~dispatchOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    dispatchOrder(orderId, dispatchRequest, callback) {
      let postBody = dispatchRequest;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling dispatchOrder");
      }
      // verify the required parameter 'dispatchRequest' is set
      if (dispatchRequest === undefined || dispatchRequest === null) {
        throw new Error("Missing the required parameter 'dispatchRequest' when calling dispatchOrder");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/api/v1/orders/{orderId}/dispatch', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderById operation.
     * @callback module:api/OrdersApi~getOrderByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get order by ID
     * @param {Number} orderId 
     * @param {module:api/OrdersApi~getOrderByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    getOrderById(orderId, callback) {
      let postBody = null;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling getOrderById");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/api/v1/orders/{orderId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderList operation.
     * @callback module:api/OrdersApi~getOrderListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PaginatedResultOrder} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get paginated list of orders
     * @param {module:model/OrderFloor} floor 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] Page number starting from 0
     * @param {Number} [size = 10)] Number of items per page
     * @param {String} [status] Filter by order status
     * @param {String} [search] Search by customer name or mobile number
     * @param {module:model/String} [sortByFields] Field to sort by
     * @param {module:model/String} [direction] Sort direction
     * @param {module:api/OrdersApi~getOrderListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PaginatedResultOrder}
     */
    getOrderList(floor, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'floor' is set
      if (floor === undefined || floor === null) {
        throw new Error("Missing the required parameter 'floor' when calling getOrderList");
      }

      let pathParams = {
        'floor': floor
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size'],
        'status': opts['status'],
        'search': opts['search'],
        'sortByFields': opts['sortByFields'],
        'direction': opts['direction']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PaginatedResultOrder;
      return this.apiClient.callApi(
        '/api/v1/orders/floor/{floor}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the revokeDispatch operation.
     * @callback module:api/OrdersApi~revokeDispatchCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Revoke a dispatched order — restores stock and deletes the order
     * Only valid when order is in DISPATCHED status. Restores deducted inventory quantities and permanently deletes the order.
     * @param {Number} orderId 
     * @param {module:model/DispatchRequest} dispatchRequest 
     * @param {module:api/OrdersApi~revokeDispatchCallback} callback The callback function, accepting three arguments: error, data, response
     */
    revokeDispatch(orderId, dispatchRequest, callback) {
      let postBody = dispatchRequest;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling revokeDispatch");
      }
      // verify the required parameter 'dispatchRequest' is set
      if (dispatchRequest === undefined || dispatchRequest === null) {
        throw new Error("Missing the required parameter 'dispatchRequest' when calling revokeDispatch");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/orders/{orderId}/revoke-dispatch', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateOrder operation.
     * @callback module:api/OrdersApi~updateOrderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update order details, billing, and product list
     * @param {Number} orderId 
     * @param {module:model/OrderRequest} orderRequest 
     * @param {module:api/OrdersApi~updateOrderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Order}
     */
    updateOrder(orderId, orderRequest, callback) {
      let postBody = orderRequest;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling updateOrder");
      }
      // verify the required parameter 'orderRequest' is set
      if (orderRequest === undefined || orderRequest === null) {
        throw new Error("Missing the required parameter 'orderRequest' when calling updateOrder");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Order;
      return this.apiClient.callApi(
        '/api/v1/orders/{orderId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateOrderStatus operation.
     * @callback module:api/OrdersApi~updateOrderStatusCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update only the status of an order
     * @param {Number} orderId 
     * @param {module:model/UpdateOrderStatusRequest} updateOrderStatusRequest 
     * @param {module:api/OrdersApi~updateOrderStatusCallback} callback The callback function, accepting three arguments: error, data, response
     */
    updateOrderStatus(orderId, updateOrderStatusRequest, callback) {
      let postBody = updateOrderStatusRequest;
      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling updateOrderStatus");
      }
      // verify the required parameter 'updateOrderStatusRequest' is set
      if (updateOrderStatusRequest === undefined || updateOrderStatusRequest === null) {
        throw new Error("Missing the required parameter 'updateOrderStatusRequest' when calling updateOrderStatus");
      }

      let pathParams = {
        'orderId': orderId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/orders/{orderId}/status', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
