/**
 * Order Management API
 * OpenAPI for order management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import NewOrderParty from '../model/NewOrderParty';
import OrderByPartyResponse from '../model/OrderByPartyResponse';
import OrderParty from '../model/OrderParty';

/**
* Party service.
* @module api/PartyApi
* @version 1.0.0
*/
export default class PartyApi {

    /**
    * Constructs a new PartyApi. 
    * @alias module:api/PartyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createParty operation.
     * @callback module:api/PartyApi~createPartyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderParty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create party
     * @param {module:model/NewOrderParty} newOrderParty 
     * @param {module:api/PartyApi~createPartyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderParty}
     */
    createParty(newOrderParty, callback) {
      let postBody = newOrderParty;
      // verify the required parameter 'newOrderParty' is set
      if (newOrderParty === undefined || newOrderParty === null) {
        throw new Error("Missing the required parameter 'newOrderParty' when calling createParty");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OrderParty;
      return this.apiClient.callApi(
        '/api/v1/parties', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteParty operation.
     * @callback module:api/PartyApi~deletePartyCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete party
     * @param {Number} id 
     * @param {module:api/PartyApi~deletePartyCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteParty(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteParty");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/parties/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllParties operation.
     * @callback module:api/PartyApi~getAllPartiesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/OrderParty>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all parties
     * @param {Object} opts Optional parameters
     * @param {String} [search] Search text to filter results by name or relevant fields
     * @param {module:api/PartyApi~getAllPartiesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/OrderParty>}
     */
    getAllParties(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [OrderParty];
      return this.apiClient.callApi(
        '/api/v1/parties', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderByPartyName operation.
     * @callback module:api/PartyApi~getOrderByPartyNameCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderByPartyResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get orders by party name
     * Returns list of all orders.
     * @param {String} partyName 
     * @param {module:api/PartyApi~getOrderByPartyNameCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderByPartyResponse}
     */
    getOrderByPartyName(partyName, callback) {
      let postBody = null;
      // verify the required parameter 'partyName' is set
      if (partyName === undefined || partyName === null) {
        throw new Error("Missing the required parameter 'partyName' when calling getOrderByPartyName");
      }

      let pathParams = {
        'partyName': partyName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrderByPartyResponse;
      return this.apiClient.callApi(
        '/api/v1/order/getByParty/{partyName}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderByPartyNamePdf operation.
     * @callback module:api/PartyApi~getOrderByPartyNamePdfCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get order by party name as pdf
     * Returns list of all orders.
     * @param {String} partyName 
     * @param {module:api/PartyApi~getOrderByPartyNamePdfCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    getOrderByPartyNamePdf(partyName, callback) {
      let postBody = null;
      // verify the required parameter 'partyName' is set
      if (partyName === undefined || partyName === null) {
        throw new Error("Missing the required parameter 'partyName' when calling getOrderByPartyNamePdf");
      }

      let pathParams = {
        'partyName': partyName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/pdf', 'application/json'];
      let returnType = File;
      return this.apiClient.callApi(
        '/api/v1/order/getByParty/{partyName}/pdf', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderListByParty operation.
     * @callback module:api/PartyApi~getOrderListByPartyCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/OrderByPartyResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all  orders By party
     * Returns list of all orders.
     * @param {Object} opts Optional parameters
     * @param {String} [search] 
     * @param {module:api/PartyApi~getOrderListByPartyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/OrderByPartyResponse>}
     */
    getOrderListByParty(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'search': opts['search']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [OrderByPartyResponse];
      return this.apiClient.callApi(
        '/api/v1/order/getByParty', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getPartyById operation.
     * @callback module:api/PartyApi~getPartyByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderParty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get party by id
     * @param {Number} id 
     * @param {module:api/PartyApi~getPartyByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderParty}
     */
    getPartyById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPartyById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = OrderParty;
      return this.apiClient.callApi(
        '/api/v1/parties/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateParty operation.
     * @callback module:api/PartyApi~updatePartyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrderParty} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update party
     * @param {Number} id 
     * @param {module:model/NewOrderParty} newOrderParty 
     * @param {module:api/PartyApi~updatePartyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrderParty}
     */
    updateParty(id, newOrderParty, callback) {
      let postBody = newOrderParty;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateParty");
      }
      // verify the required parameter 'newOrderParty' is set
      if (newOrderParty === undefined || newOrderParty === null) {
        throw new Error("Missing the required parameter 'newOrderParty' when calling updateParty");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OrderParty;
      return this.apiClient.callApi(
        '/api/v1/parties/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
