/**
 * Order Management API
 * OpenAPI for order management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DispatchItem model module.
 * @module model/DispatchItem
 * @version 1.0.0
 */
class DispatchItem {
    /**
     * Constructs a new <code>DispatchItem</code>.
     * @alias module:model/DispatchItem
     * @param itemId {Number} Reference to stock_item.item_id from inventory
     */
    constructor(itemId) { 
        
        DispatchItem.initialize(this, itemId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, itemId) { 
        obj['itemId'] = itemId;
    }

    /**
     * Constructs a <code>DispatchItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DispatchItem} obj Optional instance to populate.
     * @return {module:model/DispatchItem} The populated <code>DispatchItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DispatchItem();

            if (data.hasOwnProperty('itemId')) {
                obj['itemId'] = ApiClient.convertToType(data['itemId'], 'Number');
            }
            if (data.hasOwnProperty('quantityKg')) {
                obj['quantityKg'] = ApiClient.convertToType(data['quantityKg'], 'Number');
            }
            if (data.hasOwnProperty('quantityPc')) {
                obj['quantityPc'] = ApiClient.convertToType(data['quantityPc'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DispatchItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DispatchItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DispatchItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DispatchItem.RequiredProperties = ["itemId"];

/**
 * Reference to stock_item.item_id from inventory
 * @member {Number} itemId
 */
DispatchItem.prototype['itemId'] = undefined;

/**
 * Quantity to deduct from inventory in KG
 * @member {Number} quantityKg
 */
DispatchItem.prototype['quantityKg'] = undefined;

/**
 * Quantity to deduct from inventory in pieces
 * @member {Number} quantityPc
 */
DispatchItem.prototype['quantityPc'] = undefined;






export default DispatchItem;

