/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class InventoryStatus.
* @enum {}
* @readonly
*/
export default class InventoryStatus {
    
        /**
         * value: "IN_STOCK"
         * @const
         */
        "IN_STOCK" = "IN_STOCK";

    
        /**
         * value: "LOW_STOCK"
         * @const
         */
        "LOW_STOCK" = "LOW_STOCK";

    

    /**
    * Returns a <code>InventoryStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InventoryStatus} The enum <code>InventoryStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

