/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class InventoryExistStatus.
* @enum {}
* @readonly
*/
export default class InventoryExistStatus {
    
        /**
         * value: "CREATED"
         * @const
         */
        "CREATED" = "CREATED";

    
        /**
         * value: "ALREADY_EXISTS"
         * @const
         */
        "ALREADY_EXISTS" = "ALREADY_EXISTS";

    

    /**
    * Returns a <code>InventoryExistStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/InventoryExistStatus} The enum <code>InventoryExistStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

