/**
 * Order Management API
 * OpenAPI for order management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OrderFloor from './OrderFloor';
import OrderProductRequest from './OrderProductRequest';

/**
 * The OrderRequest model module.
 * @module model/OrderRequest
 * @version 1.0.0
 */
class OrderRequest {
    /**
     * Constructs a new <code>OrderRequest</code>.
     * @alias module:model/OrderRequest
     * @param customerName {String} 
     * @param orderDate {Date} 
     * @param expectedDeliveryDate {Date} 
     */
    constructor(customerName, orderDate, expectedDeliveryDate) { 
        
        OrderRequest.initialize(this, customerName, orderDate, expectedDeliveryDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, customerName, orderDate, expectedDeliveryDate) { 
        obj['customerName'] = customerName;
        obj['orderDate'] = orderDate;
        obj['expectedDeliveryDate'] = expectedDeliveryDate;
    }

    /**
     * Constructs a <code>OrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderRequest} obj Optional instance to populate.
     * @return {module:model/OrderRequest} The populated <code>OrderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderRequest();

            if (data.hasOwnProperty('customerName')) {
                obj['customerName'] = ApiClient.convertToType(data['customerName'], 'String');
            }
            if (data.hasOwnProperty('customerMobileNo')) {
                obj['customerMobileNo'] = ApiClient.convertToType(data['customerMobileNo'], 'String');
            }
            if (data.hasOwnProperty('customerEmail')) {
                obj['customerEmail'] = ApiClient.convertToType(data['customerEmail'], 'String');
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('expectedDeliveryDate')) {
                obj['expectedDeliveryDate'] = ApiClient.convertToType(data['expectedDeliveryDate'], 'Date');
            }
            if (data.hasOwnProperty('paymentDate')) {
                obj['paymentDate'] = ApiClient.convertToType(data['paymentDate'], 'Date');
            }
            if (data.hasOwnProperty('totalItems')) {
                obj['totalItems'] = ApiClient.convertToType(data['totalItems'], 'Number');
            }
            if (data.hasOwnProperty('orderFloor')) {
                obj['orderFloor'] = OrderFloor.constructFromObject(data['orderFloor']);
            }
            if (data.hasOwnProperty('offlineBillPercent')) {
                obj['offlineBillPercent'] = ApiClient.convertToType(data['offlineBillPercent'], 'Number');
            }
            if (data.hasOwnProperty('offlineTotal')) {
                obj['offlineTotal'] = ApiClient.convertToType(data['offlineTotal'], 'Number');
            }
            if (data.hasOwnProperty('officialBillAmount')) {
                obj['officialBillAmount'] = ApiClient.convertToType(data['officialBillAmount'], 'Number');
            }
            if (data.hasOwnProperty('gst')) {
                obj['gst'] = ApiClient.convertToType(data['gst'], 'Number');
            }
            if (data.hasOwnProperty('grandTotal')) {
                obj['grandTotal'] = ApiClient.convertToType(data['grandTotal'], 'Number');
            }
            if (data.hasOwnProperty('productsTotal')) {
                obj['productsTotal'] = ApiClient.convertToType(data['productsTotal'], 'Number');
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [OrderProductRequest]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrderRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['customerName'] && !(typeof data['customerName'] === 'string' || data['customerName'] instanceof String)) {
            throw new Error("Expected the field `customerName` to be a primitive type in the JSON string but got " + data['customerName']);
        }
        // ensure the json data is a string
        if (data['customerMobileNo'] && !(typeof data['customerMobileNo'] === 'string' || data['customerMobileNo'] instanceof String)) {
            throw new Error("Expected the field `customerMobileNo` to be a primitive type in the JSON string but got " + data['customerMobileNo']);
        }
        // ensure the json data is a string
        if (data['customerEmail'] && !(typeof data['customerEmail'] === 'string' || data['customerEmail'] instanceof String)) {
            throw new Error("Expected the field `customerEmail` to be a primitive type in the JSON string but got " + data['customerEmail']);
        }
        if (data['products']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['products'])) {
                throw new Error("Expected the field `products` to be an array in the JSON data but got " + data['products']);
            }
            // validate the optional field `products` (array)
            for (const item of data['products']) {
                OrderProductRequest.validateJSON(item);
            };
        }

        return true;
    }


}

OrderRequest.RequiredProperties = ["customerName", "orderDate", "expectedDeliveryDate"];

/**
 * @member {String} customerName
 */
OrderRequest.prototype['customerName'] = undefined;

/**
 * @member {String} customerMobileNo
 */
OrderRequest.prototype['customerMobileNo'] = undefined;

/**
 * @member {String} customerEmail
 */
OrderRequest.prototype['customerEmail'] = undefined;

/**
 * @member {Date} orderDate
 */
OrderRequest.prototype['orderDate'] = undefined;

/**
 * @member {Date} expectedDeliveryDate
 */
OrderRequest.prototype['expectedDeliveryDate'] = undefined;

/**
 * @member {Date} paymentDate
 */
OrderRequest.prototype['paymentDate'] = undefined;

/**
 * @member {Number} totalItems
 */
OrderRequest.prototype['totalItems'] = undefined;

/**
 * @member {module:model/OrderFloor} orderFloor
 */
OrderRequest.prototype['orderFloor'] = undefined;

/**
 * @member {Number} offlineBillPercent
 */
OrderRequest.prototype['offlineBillPercent'] = undefined;

/**
 * @member {Number} offlineTotal
 */
OrderRequest.prototype['offlineTotal'] = undefined;

/**
 * @member {Number} officialBillAmount
 */
OrderRequest.prototype['officialBillAmount'] = undefined;

/**
 * @member {Number} gst
 */
OrderRequest.prototype['gst'] = undefined;

/**
 * @member {Number} grandTotal
 */
OrderRequest.prototype['grandTotal'] = undefined;

/**
 * @member {Number} productsTotal
 */
OrderRequest.prototype['productsTotal'] = undefined;

/**
 * @member {Array.<module:model/OrderProductRequest>} products
 */
OrderRequest.prototype['products'] = undefined;






export default OrderRequest;

