/**
 * Order Management API
 * OpenAPI for order management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderProductRequest model module.
 * @module model/OrderProductRequest
 * @version 1.0.0
 */
class OrderProductRequest {
    /**
     * Constructs a new <code>OrderProductRequest</code>.
     * @alias module:model/OrderProductRequest
     * @param itemId {Number} Reference to stock_item.item_id from inventory
     * @param marketRate {Number} 
     * @param rateDifference {Number} 
     * @param totalAmount {Number} 
     */
    constructor(itemId, marketRate, rateDifference, totalAmount) { 
        
        OrderProductRequest.initialize(this, itemId, marketRate, rateDifference, totalAmount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, itemId, marketRate, rateDifference, totalAmount) { 
        obj['itemId'] = itemId;
        obj['marketRate'] = marketRate;
        obj['rateDifference'] = rateDifference;
        obj['totalAmount'] = totalAmount;
    }

    /**
     * Constructs a <code>OrderProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderProductRequest} obj Optional instance to populate.
     * @return {module:model/OrderProductRequest} The populated <code>OrderProductRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderProductRequest();

            if (data.hasOwnProperty('itemId')) {
                obj['itemId'] = ApiClient.convertToType(data['itemId'], 'Number');
            }
            if (data.hasOwnProperty('quantityKg')) {
                obj['quantityKg'] = ApiClient.convertToType(data['quantityKg'], 'Number');
            }
            if (data.hasOwnProperty('quantityPc')) {
                obj['quantityPc'] = ApiClient.convertToType(data['quantityPc'], 'Number');
            }
            if (data.hasOwnProperty('marketRate')) {
                obj['marketRate'] = ApiClient.convertToType(data['marketRate'], 'Number');
            }
            if (data.hasOwnProperty('rateDifference')) {
                obj['rateDifference'] = ApiClient.convertToType(data['rateDifference'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderProductRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderProductRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrderProductRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

OrderProductRequest.RequiredProperties = ["itemId", "marketRate", "rateDifference", "totalAmount"];

/**
 * Reference to stock_item.item_id from inventory
 * @member {Number} itemId
 */
OrderProductRequest.prototype['itemId'] = undefined;

/**
 * @member {Number} quantityKg
 */
OrderProductRequest.prototype['quantityKg'] = undefined;

/**
 * @member {Number} quantityPc
 */
OrderProductRequest.prototype['quantityPc'] = undefined;

/**
 * @member {Number} marketRate
 */
OrderProductRequest.prototype['marketRate'] = undefined;

/**
 * @member {Number} rateDifference
 */
OrderProductRequest.prototype['rateDifference'] = undefined;

/**
 * @member {Number} totalAmount
 */
OrderProductRequest.prototype['totalAmount'] = undefined;






export default OrderProductRequest;

