/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StockItem from './StockItem';

/**
 * The PaginatedResultStockItem model module.
 * @module model/PaginatedResultStockItem
 * @version 1.0.0
 */
class PaginatedResultStockItem {
    /**
     * Constructs a new <code>PaginatedResultStockItem</code>.
     * @alias module:model/PaginatedResultStockItem
     */
    constructor() { 
        
        PaginatedResultStockItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginatedResultStockItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedResultStockItem} obj Optional instance to populate.
     * @return {module:model/PaginatedResultStockItem} The populated <code>PaginatedResultStockItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedResultStockItem();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [StockItem]);
            }
            if (data.hasOwnProperty('empty')) {
                obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaginatedResultStockItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaginatedResultStockItem</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                StockItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/StockItem>} data
 */
PaginatedResultStockItem.prototype['data'] = undefined;

/**
 * @member {Boolean} empty
 */
PaginatedResultStockItem.prototype['empty'] = undefined;

/**
 * @member {Boolean} last
 */
PaginatedResultStockItem.prototype['last'] = undefined;

/**
 * @member {Boolean} first
 */
PaginatedResultStockItem.prototype['first'] = undefined;

/**
 * @member {Number} totalPages
 */
PaginatedResultStockItem.prototype['totalPages'] = undefined;

/**
 * @member {Number} totalElements
 */
PaginatedResultStockItem.prototype['totalElements'] = undefined;

/**
 * @member {Number} size
 */
PaginatedResultStockItem.prototype['size'] = undefined;






export default PaginatedResultStockItem;

