/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PurchaseInventoryType.
* @enum {}
* @readonly
*/
export default class PurchaseInventoryType {
    
        /**
         * value: "RAW_MATERIAL"
         * @const
         */
        "RAW_MATERIAL" = "RAW_MATERIAL";

    
        /**
         * value: "GROUND_FLOOR"
         * @const
         */
        "GROUND_FLOOR" = "GROUND_FLOOR";

    
        /**
         * value: "FIRST_FLOOR"
         * @const
         */
        "FIRST_FLOOR" = "FIRST_FLOOR";

    

    /**
    * Returns a <code>PurchaseInventoryType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PurchaseInventoryType} The enum <code>PurchaseInventoryType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

