/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryStatus from './InventoryStatus';
import Product from './Product';

/**
 * The RawItem model module.
 * @module model/RawItem
 * @version 1.0.0
 */
class RawItem {
    /**
     * Constructs a new <code>RawItem</code>.
     * @alias module:model/RawItem
     */
    constructor() { 
        
        RawItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RawItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RawItem} obj Optional instance to populate.
     * @return {module:model/RawItem} The populated <code>RawItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawItem();

            if (data.hasOwnProperty('rawItemId')) {
                obj['rawItemId'] = ApiClient.convertToType(data['rawItemId'], 'Number');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = Product.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('quantityInKg')) {
                obj['quantityInKg'] = ApiClient.convertToType(data['quantityInKg'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = InventoryStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('lowStockAlert')) {
                obj['lowStockAlert'] = ApiClient.convertToType(data['lowStockAlert'], 'Number');
            }
            if (data.hasOwnProperty('lastUpdatedAt')) {
                obj['lastUpdatedAt'] = ApiClient.convertToType(data['lastUpdatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RawItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RawItem</code>.
     */
    static validateJSON(data) {
        // validate the optional field `product`
        if (data['product']) { // data not null
          Product.validateJSON(data['product']);
        }

        return true;
    }


}



/**
 * @member {Number} rawItemId
 */
RawItem.prototype['rawItemId'] = undefined;

/**
 * @member {module:model/Product} product
 */
RawItem.prototype['product'] = undefined;

/**
 * @member {Number} quantityInKg
 */
RawItem.prototype['quantityInKg'] = undefined;

/**
 * @member {module:model/InventoryStatus} status
 */
RawItem.prototype['status'] = undefined;

/**
 * @member {Number} lowStockAlert
 */
RawItem.prototype['lowStockAlert'] = undefined;

/**
 * @member {Date} lastUpdatedAt
 */
RawItem.prototype['lastUpdatedAt'] = undefined;






export default RawItem;

