/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryStatus from './InventoryStatus';

/**
 * The RawItemRequest model module.
 * @module model/RawItemRequest
 * @version 1.0.0
 */
class RawItemRequest {
    /**
     * Constructs a new <code>RawItemRequest</code>.
     * @alias module:model/RawItemRequest
     * @param productId {Number} 
     * @param quantityInKg {Number} 
     * @param lowStockAlert {Number} 
     */
    constructor(productId, quantityInKg, lowStockAlert) { 
        
        RawItemRequest.initialize(this, productId, quantityInKg, lowStockAlert);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, quantityInKg, lowStockAlert) { 
        obj['productId'] = productId;
        obj['quantityInKg'] = quantityInKg;
        obj['lowStockAlert'] = lowStockAlert;
    }

    /**
     * Constructs a <code>RawItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RawItemRequest} obj Optional instance to populate.
     * @return {module:model/RawItemRequest} The populated <code>RawItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawItemRequest();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('quantityInKg')) {
                obj['quantityInKg'] = ApiClient.convertToType(data['quantityInKg'], 'Number');
            }
            if (data.hasOwnProperty('lowStockAlert')) {
                obj['lowStockAlert'] = ApiClient.convertToType(data['lowStockAlert'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = InventoryStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RawItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RawItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RawItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

RawItemRequest.RequiredProperties = ["productId", "quantityInKg", "lowStockAlert"];

/**
 * @member {Number} productId
 */
RawItemRequest.prototype['productId'] = undefined;

/**
 * @member {Number} quantityInKg
 */
RawItemRequest.prototype['quantityInKg'] = undefined;

/**
 * @member {Number} lowStockAlert
 */
RawItemRequest.prototype['lowStockAlert'] = undefined;

/**
 * @member {module:model/InventoryStatus} status
 */
RawItemRequest.prototype['status'] = undefined;






export default RawItemRequest;

