/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PurchaseParty from './PurchaseParty';
import ReturnType from './ReturnType';
import StockItem from './StockItem';

/**
 * The RejectionResponse model module.
 * @module model/RejectionResponse
 * @version 1.0.0
 */
class RejectionResponse {
    /**
     * Constructs a new <code>RejectionResponse</code>.
     * @alias module:model/RejectionResponse
     */
    constructor() { 
        
        RejectionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RejectionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RejectionResponse} obj Optional instance to populate.
     * @return {module:model/RejectionResponse} The populated <code>RejectionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RejectionResponse();

            if (data.hasOwnProperty('rejectionId')) {
                obj['rejectionId'] = ApiClient.convertToType(data['rejectionId'], 'Number');
            }
            if (data.hasOwnProperty('party')) {
                obj['party'] = PurchaseParty.constructFromObject(data['party']);
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
            if (data.hasOwnProperty('returnType')) {
                obj['returnType'] = ReturnType.constructFromObject(data['returnType']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('stockItem')) {
                obj['stockItem'] = StockItem.constructFromObject(data['stockItem']);
            }
            if (data.hasOwnProperty('returnQty')) {
                obj['returnQty'] = ApiClient.convertToType(data['returnQty'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RejectionResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RejectionResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `party`
        if (data['party']) { // data not null
          PurchaseParty.validateJSON(data['party']);
        }
        // validate the optional field `stockItem`
        if (data['stockItem']) { // data not null
          StockItem.validateJSON(data['stockItem']);
        }

        return true;
    }


}



/**
 * @member {Number} rejectionId
 */
RejectionResponse.prototype['rejectionId'] = undefined;

/**
 * @member {module:model/PurchaseParty} party
 */
RejectionResponse.prototype['party'] = undefined;

/**
 * @member {Date} date
 */
RejectionResponse.prototype['date'] = undefined;

/**
 * @member {Number} weight
 */
RejectionResponse.prototype['weight'] = undefined;

/**
 * @member {module:model/ReturnType} returnType
 */
RejectionResponse.prototype['returnType'] = undefined;

/**
 * @member {Number} amount
 */
RejectionResponse.prototype['amount'] = undefined;

/**
 * @member {module:model/StockItem} stockItem
 */
RejectionResponse.prototype['stockItem'] = undefined;

/**
 * @member {Number} returnQty
 */
RejectionResponse.prototype['returnQty'] = undefined;






export default RejectionResponse;

