/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ImageMetadata from './ImageMetadata';
import InventoryFloor from './InventoryFloor';
import InventoryStatus from './InventoryStatus';
import QuantityUnit from './QuantityUnit';

/**
 * The StockItemRequest model module.
 * @module model/StockItemRequest
 * @version 1.0.0
 */
class StockItemRequest {
    /**
     * Constructs a new <code>StockItemRequest</code>.
     * @alias module:model/StockItemRequest
     * @param productId {Number} 
     * @param categoryId {Number} 
     * @param quantityInKg {Number} 
     * @param quantityInPc {Number} 
     * @param weightPerPc {Number} 
     * @param pricePerKg {Number} 
     * @param quantityUnit {module:model/QuantityUnit} 
     * @param lowStockAlert {Number} 
     */
    constructor(productId, categoryId, quantityInKg, quantityInPc, weightPerPc, pricePerKg, quantityUnit, lowStockAlert) { 
        
        StockItemRequest.initialize(this, productId, categoryId, quantityInKg, quantityInPc, weightPerPc, pricePerKg, quantityUnit, lowStockAlert);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, categoryId, quantityInKg, quantityInPc, weightPerPc, pricePerKg, quantityUnit, lowStockAlert) { 
        obj['productId'] = productId;
        obj['categoryId'] = categoryId;
        obj['quantityInKg'] = quantityInKg;
        obj['quantityInPc'] = quantityInPc;
        obj['weightPerPc'] = weightPerPc;
        obj['pricePerKg'] = pricePerKg;
        obj['quantityUnit'] = quantityUnit;
        obj['lowStockAlert'] = lowStockAlert;
    }

    /**
     * Constructs a <code>StockItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StockItemRequest} obj Optional instance to populate.
     * @return {module:model/StockItemRequest} The populated <code>StockItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StockItemRequest();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('categoryId')) {
                obj['categoryId'] = ApiClient.convertToType(data['categoryId'], 'Number');
            }
            if (data.hasOwnProperty('quantityInKg')) {
                obj['quantityInKg'] = ApiClient.convertToType(data['quantityInKg'], 'Number');
            }
            if (data.hasOwnProperty('quantityInPc')) {
                obj['quantityInPc'] = ApiClient.convertToType(data['quantityInPc'], 'Number');
            }
            if (data.hasOwnProperty('weightPerPc')) {
                obj['weightPerPc'] = ApiClient.convertToType(data['weightPerPc'], 'Number');
            }
            if (data.hasOwnProperty('pricePerKg')) {
                obj['pricePerKg'] = ApiClient.convertToType(data['pricePerKg'], 'Number');
            }
            if (data.hasOwnProperty('quantityUnit')) {
                obj['quantityUnit'] = QuantityUnit.constructFromObject(data['quantityUnit']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = InventoryStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('inventoryFloor')) {
                obj['inventoryFloor'] = InventoryFloor.constructFromObject(data['inventoryFloor']);
            }
            if (data.hasOwnProperty('lowStockAlert')) {
                obj['lowStockAlert'] = ApiClient.convertToType(data['lowStockAlert'], 'Number');
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ApiClient.convertToType(data['images'], [ImageMetadata]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StockItemRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StockItemRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StockItemRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['images']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['images'])) {
                throw new Error("Expected the field `images` to be an array in the JSON data but got " + data['images']);
            }
            // validate the optional field `images` (array)
            for (const item of data['images']) {
                ImageMetadata.validateJSON(item);
            };
        }

        return true;
    }


}

StockItemRequest.RequiredProperties = ["productId", "categoryId", "quantityInKg", "quantityInPc", "weightPerPc", "pricePerKg", "quantityUnit", "lowStockAlert"];

/**
 * @member {Number} productId
 */
StockItemRequest.prototype['productId'] = undefined;

/**
 * @member {Number} categoryId
 */
StockItemRequest.prototype['categoryId'] = undefined;

/**
 * @member {Number} quantityInKg
 */
StockItemRequest.prototype['quantityInKg'] = undefined;

/**
 * @member {Number} quantityInPc
 */
StockItemRequest.prototype['quantityInPc'] = undefined;

/**
 * @member {Number} weightPerPc
 */
StockItemRequest.prototype['weightPerPc'] = undefined;

/**
 * @member {Number} pricePerKg
 */
StockItemRequest.prototype['pricePerKg'] = undefined;

/**
 * @member {module:model/QuantityUnit} quantityUnit
 */
StockItemRequest.prototype['quantityUnit'] = undefined;

/**
 * @member {module:model/InventoryStatus} status
 */
StockItemRequest.prototype['status'] = undefined;

/**
 * @member {module:model/InventoryFloor} inventoryFloor
 */
StockItemRequest.prototype['inventoryFloor'] = undefined;

/**
 * @member {Number} lowStockAlert
 */
StockItemRequest.prototype['lowStockAlert'] = undefined;

/**
 * Array of image metadata (name and location)
 * @member {Array.<module:model/ImageMetadata>} images
 */
StockItemRequest.prototype['images'] = undefined;






export default StockItemRequest;

