/**
 * Inventory API
 * OpenAPI for inventory management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryStatus from './InventoryStatus';

/**
 * The UpdateStockItemStatusRequest model module.
 * @module model/UpdateStockItemStatusRequest
 * @version 1.0.0
 */
class UpdateStockItemStatusRequest {
    /**
     * Constructs a new <code>UpdateStockItemStatusRequest</code>.
     * @alias module:model/UpdateStockItemStatusRequest
     * @param status {module:model/InventoryStatus} 
     */
    constructor(status) { 
        
        UpdateStockItemStatusRequest.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>UpdateStockItemStatusRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateStockItemStatusRequest} obj Optional instance to populate.
     * @return {module:model/UpdateStockItemStatusRequest} The populated <code>UpdateStockItemStatusRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateStockItemStatusRequest();

            if (data.hasOwnProperty('status')) {
                obj['status'] = InventoryStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateStockItemStatusRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateStockItemStatusRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateStockItemStatusRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

UpdateStockItemStatusRequest.RequiredProperties = ["status"];

/**
 * @member {module:model/InventoryStatus} status
 */
UpdateStockItemStatusRequest.prototype['status'] = undefined;






export default UpdateStockItemStatusRequest;

