/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Contractor model module.
 * @module model/Contractor
 * @version 1.0.0
 */
class Contractor {
    /**
     * Constructs a new <code>Contractor</code>.
     * @alias module:model/Contractor
     */
    constructor() { 
        
        Contractor.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Contractor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Contractor} obj Optional instance to populate.
     * @return {module:model/Contractor} The populated <code>Contractor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Contractor();

            if (data.hasOwnProperty('contractorId')) {
                obj['contractorId'] = ApiClient.convertToType(data['contractorId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Contractor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Contractor</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {Number} contractorId
 */
Contractor.prototype['contractorId'] = undefined;

/**
 * @member {String} name
 */
Contractor.prototype['name'] = undefined;






export default Contractor;

