/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CromeReportItem from './CromeReportItem';

/**
 * The CromeReportList model module.
 * @module model/CromeReportList
 * @version 1.0.0
 */
class CromeReportList {
    /**
     * Constructs a new <code>CromeReportList</code>.
     * Crome report data for PDF generation
     * @alias module:model/CromeReportList
     */
    constructor() { 
        
        CromeReportList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CromeReportList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CromeReportList} obj Optional instance to populate.
     * @return {module:model/CromeReportList} The populated <code>CromeReportList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CromeReportList();

            if (data.hasOwnProperty('partyName')) {
                obj['partyName'] = ApiClient.convertToType(data['partyName'], 'String');
            }
            if (data.hasOwnProperty('cromeList')) {
                obj['cromeList'] = ApiClient.convertToType(data['cromeList'], [CromeReportItem]);
            }
            if (data.hasOwnProperty('totalSentStock')) {
                obj['totalSentStock'] = ApiClient.convertToType(data['totalSentStock'], 'Number');
            }
            if (data.hasOwnProperty('totalGrossWeight')) {
                obj['totalGrossWeight'] = ApiClient.convertToType(data['totalGrossWeight'], 'Number');
            }
            if (data.hasOwnProperty('totalReturnStock')) {
                obj['totalReturnStock'] = ApiClient.convertToType(data['totalReturnStock'], 'Number');
            }
            if (data.hasOwnProperty('totalNetReturnStock')) {
                obj['totalNetReturnStock'] = ApiClient.convertToType(data['totalNetReturnStock'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CromeReportList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CromeReportList</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['partyName'] && !(typeof data['partyName'] === 'string' || data['partyName'] instanceof String)) {
            throw new Error("Expected the field `partyName` to be a primitive type in the JSON string but got " + data['partyName']);
        }
        if (data['cromeList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cromeList'])) {
                throw new Error("Expected the field `cromeList` to be an array in the JSON data but got " + data['cromeList']);
            }
            // validate the optional field `cromeList` (array)
            for (const item of data['cromeList']) {
                CromeReportItem.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} partyName
 */
CromeReportList.prototype['partyName'] = undefined;

/**
 * @member {Array.<module:model/CromeReportItem>} cromeList
 */
CromeReportList.prototype['cromeList'] = undefined;

/**
 * Total stock sent for crome
 * @member {Number} totalSentStock
 */
CromeReportList.prototype['totalSentStock'] = undefined;

/**
 * Total gross weight including packaging
 * @member {Number} totalGrossWeight
 */
CromeReportList.prototype['totalGrossWeight'] = undefined;

/**
 * Total stock returned from crome
 * @member {Number} totalReturnStock
 */
CromeReportList.prototype['totalReturnStock'] = undefined;

/**
 * Total net stock after return deductions
 * @member {Number} totalNetReturnStock
 */
CromeReportList.prototype['totalNetReturnStock'] = undefined;






export default CromeReportList;

