/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryFloor from './InventoryFloor';
import PackagingDetail from './PackagingDetail';

/**
 * The CromeReturnRequest model module.
 * @module model/CromeReturnRequest
 * @version 1.0.0
 */
class CromeReturnRequest {
    /**
     * Constructs a new <code>CromeReturnRequest</code>.
     * @alias module:model/CromeReturnRequest
     * @param returnDate {Date} 
     * @param packagings {Array.<module:model/PackagingDetail>} 
     */
    constructor(returnDate, packagings) { 
        
        CromeReturnRequest.initialize(this, returnDate, packagings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, returnDate, packagings) { 
        obj['returnDate'] = returnDate;
        obj['packagings'] = packagings;
    }

    /**
     * Constructs a <code>CromeReturnRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CromeReturnRequest} obj Optional instance to populate.
     * @return {module:model/CromeReturnRequest} The populated <code>CromeReturnRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CromeReturnRequest();

            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Date');
            }
            if (data.hasOwnProperty('returnStock')) {
                obj['returnStock'] = ApiClient.convertToType(data['returnStock'], 'Number');
            }
            if (data.hasOwnProperty('packagings')) {
                obj['packagings'] = ApiClient.convertToType(data['packagings'], [PackagingDetail]);
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
            if (data.hasOwnProperty('returnRemark')) {
                obj['returnRemark'] = ApiClient.convertToType(data['returnRemark'], 'String');
            }
            if (data.hasOwnProperty('addToInventory')) {
                obj['addToInventory'] = ApiClient.convertToType(data['addToInventory'], 'Boolean');
            }
            if (data.hasOwnProperty('inventoryItemName')) {
                obj['inventoryItemName'] = ApiClient.convertToType(data['inventoryItemName'], 'String');
            }
            if (data.hasOwnProperty('inventoryFloor')) {
                obj['inventoryFloor'] = InventoryFloor.constructFromObject(data['inventoryFloor']);
            }
            if (data.hasOwnProperty('inventoryPricePerKg')) {
                obj['inventoryPricePerKg'] = ApiClient.convertToType(data['inventoryPricePerKg'], 'Number');
            }
            if (data.hasOwnProperty('inventoryQuantityPc')) {
                obj['inventoryQuantityPc'] = ApiClient.convertToType(data['inventoryQuantityPc'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CromeReturnRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CromeReturnRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CromeReturnRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['packagings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['packagings'])) {
                throw new Error("Expected the field `packagings` to be an array in the JSON data but got " + data['packagings']);
            }
            // validate the optional field `packagings` (array)
            for (const item of data['packagings']) {
                PackagingDetail.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['returnRemark'] && !(typeof data['returnRemark'] === 'string' || data['returnRemark'] instanceof String)) {
            throw new Error("Expected the field `returnRemark` to be a primitive type in the JSON string but got " + data['returnRemark']);
        }
        // ensure the json data is a string
        if (data['inventoryItemName'] && !(typeof data['inventoryItemName'] === 'string' || data['inventoryItemName'] instanceof String)) {
            throw new Error("Expected the field `inventoryItemName` to be a primitive type in the JSON string but got " + data['inventoryItemName']);
        }

        return true;
    }


}

CromeReturnRequest.RequiredProperties = ["returnDate", "packagings"];

/**
 * @member {Date} returnDate
 */
CromeReturnRequest.prototype['returnDate'] = undefined;

/**
 * Gross stock returned from crome
 * @member {Number} returnStock
 */
CromeReturnRequest.prototype['returnStock'] = undefined;

/**
 * @member {Array.<module:model/PackagingDetail>} packagings
 */
CromeReturnRequest.prototype['packagings'] = undefined;

/**
 * Rate for the returned crome item
 * @member {Number} rate
 */
CromeReturnRequest.prototype['rate'] = undefined;

/**
 * @member {String} returnRemark
 */
CromeReturnRequest.prototype['returnRemark'] = undefined;

/**
 * Whether to add the returned item to inventory
 * @member {Boolean} addToInventory
 */
CromeReturnRequest.prototype['addToInventory'] = undefined;

/**
 * Name of the item to add to inventory (e.g. \"Item Name from crome\")
 * @member {String} inventoryItemName
 */
CromeReturnRequest.prototype['inventoryItemName'] = undefined;

/**
 * @member {module:model/InventoryFloor} inventoryFloor
 */
CromeReturnRequest.prototype['inventoryFloor'] = undefined;

/**
 * Price per KG for the inventory item
 * @member {Number} inventoryPricePerKg
 */
CromeReturnRequest.prototype['inventoryPricePerKg'] = undefined;

/**
 * Quantity in Pieces for the inventory item
 * @member {Number} inventoryQuantityPc
 */
CromeReturnRequest.prototype['inventoryQuantityPc'] = undefined;






export default CromeReturnRequest;

