/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PackagingDetail from './PackagingDetail';

/**
 * The CromeReturn model module.
 * @module model/CromeReturn
 * @version 1.0.0
 */
class CromeReturn {
    /**
     * Constructs a new <code>CromeReturn</code>.
     * Return details for a crome order
     * @alias module:model/CromeReturn
     */
    constructor() { 
        
        CromeReturn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CromeReturn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CromeReturn} obj Optional instance to populate.
     * @return {module:model/CromeReturn} The populated <code>CromeReturn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CromeReturn();

            if (data.hasOwnProperty('cromeReturnId')) {
                obj['cromeReturnId'] = ApiClient.convertToType(data['cromeReturnId'], 'Number');
            }
            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Date');
            }
            if (data.hasOwnProperty('returnStock')) {
                obj['returnStock'] = ApiClient.convertToType(data['returnStock'], 'Number');
            }
            if (data.hasOwnProperty('netReturnStock')) {
                obj['netReturnStock'] = ApiClient.convertToType(data['netReturnStock'], 'Number');
            }
            if (data.hasOwnProperty('packagings')) {
                obj['packagings'] = ApiClient.convertToType(data['packagings'], [PackagingDetail]);
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('returnRemark')) {
                obj['returnRemark'] = ApiClient.convertToType(data['returnRemark'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CromeReturn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CromeReturn</code>.
     */
    static validateJSON(data) {
        if (data['packagings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['packagings'])) {
                throw new Error("Expected the field `packagings` to be an array in the JSON data but got " + data['packagings']);
            }
            // validate the optional field `packagings` (array)
            for (const item of data['packagings']) {
                PackagingDetail.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['returnRemark'] && !(typeof data['returnRemark'] === 'string' || data['returnRemark'] instanceof String)) {
            throw new Error("Expected the field `returnRemark` to be a primitive type in the JSON string but got " + data['returnRemark']);
        }

        return true;
    }


}



/**
 * @member {Number} cromeReturnId
 */
CromeReturn.prototype['cromeReturnId'] = undefined;

/**
 * @member {Date} returnDate
 */
CromeReturn.prototype['returnDate'] = undefined;

/**
 * Gross stock returned
 * @member {Number} returnStock
 */
CromeReturn.prototype['returnStock'] = undefined;

/**
 * Net stock after deducting packaging (returnStock - packagingWeight * packagingCount)
 * @member {Number} netReturnStock
 */
CromeReturn.prototype['netReturnStock'] = undefined;

/**
 * @member {Array.<module:model/PackagingDetail>} packagings
 */
CromeReturn.prototype['packagings'] = undefined;

/**
 * @member {Number} rate
 */
CromeReturn.prototype['rate'] = undefined;

/**
 * @member {Number} amount
 */
CromeReturn.prototype['amount'] = undefined;

/**
 * @member {String} returnRemark
 */
CromeReturn.prototype['returnRemark'] = undefined;






export default CromeReturn;

