/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PackagingType from './PackagingType';

/**
 * The PackagingDetail model module.
 * @module model/PackagingDetail
 * @version 1.0.0
 */
class PackagingDetail {
    /**
     * Constructs a new <code>PackagingDetail</code>.
     * @alias module:model/PackagingDetail
     * @param packagingType {module:model/PackagingType} 
     * @param packagingWeight {Number} Weight per packaging unit in KG
     * @param packagingCount {Number} Number of packaging units
     */
    constructor(packagingType, packagingWeight, packagingCount) { 
        
        PackagingDetail.initialize(this, packagingType, packagingWeight, packagingCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, packagingType, packagingWeight, packagingCount) { 
        obj['packagingType'] = packagingType;
        obj['packagingWeight'] = packagingWeight;
        obj['packagingCount'] = packagingCount;
    }

    /**
     * Constructs a <code>PackagingDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackagingDetail} obj Optional instance to populate.
     * @return {module:model/PackagingDetail} The populated <code>PackagingDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackagingDetail();

            if (data.hasOwnProperty('packagingType')) {
                obj['packagingType'] = PackagingType.constructFromObject(data['packagingType']);
            }
            if (data.hasOwnProperty('packagingWeight')) {
                obj['packagingWeight'] = ApiClient.convertToType(data['packagingWeight'], 'Number');
            }
            if (data.hasOwnProperty('packagingCount')) {
                obj['packagingCount'] = ApiClient.convertToType(data['packagingCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PackagingDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PackagingDetail</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PackagingDetail.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PackagingDetail.RequiredProperties = ["packagingType", "packagingWeight", "packagingCount"];

/**
 * @member {module:model/PackagingType} packagingType
 */
PackagingDetail.prototype['packagingType'] = undefined;

/**
 * Weight per packaging unit in KG
 * @member {Number} packagingWeight
 */
PackagingDetail.prototype['packagingWeight'] = undefined;

/**
 * Number of packaging units
 * @member {Number} packagingCount
 */
PackagingDetail.prototype['packagingCount'] = undefined;






export default PackagingDetail;

