/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Crome from './Crome';

/**
 * The PaginatedResultCrome model module.
 * @module model/PaginatedResultCrome
 * @version 1.0.0
 */
class PaginatedResultCrome {
    /**
     * Constructs a new <code>PaginatedResultCrome</code>.
     * @alias module:model/PaginatedResultCrome
     */
    constructor() { 
        
        PaginatedResultCrome.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginatedResultCrome</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedResultCrome} obj Optional instance to populate.
     * @return {module:model/PaginatedResultCrome} The populated <code>PaginatedResultCrome</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedResultCrome();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Crome]);
            }
            if (data.hasOwnProperty('empty')) {
                obj['empty'] = ApiClient.convertToType(data['empty'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaginatedResultCrome</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaginatedResultCrome</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                Crome.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Crome>} data
 */
PaginatedResultCrome.prototype['data'] = undefined;

/**
 * Indicates if the current page is empty
 * @member {Boolean} empty
 */
PaginatedResultCrome.prototype['empty'] = undefined;

/**
 * Indicates if the current page is the last page
 * @member {Boolean} last
 */
PaginatedResultCrome.prototype['last'] = undefined;

/**
 * Indicates if the current page is the first page
 * @member {Boolean} first
 */
PaginatedResultCrome.prototype['first'] = undefined;

/**
 * Total number of pages available
 * @member {Number} totalPages
 */
PaginatedResultCrome.prototype['totalPages'] = undefined;

/**
 * Total number of elements
 * @member {Number} totalElements
 */
PaginatedResultCrome.prototype['totalElements'] = undefined;

/**
 * Number of items per page
 * @member {Number} size
 */
PaginatedResultCrome.prototype['size'] = undefined;






export default PaginatedResultCrome;

