/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubcontractingBySubcontractInfo model module.
 * @module model/SubcontractingBySubcontractInfo
 * @version 1.0.0
 */
class SubcontractingBySubcontractInfo {
    /**
     * Constructs a new <code>SubcontractingBySubcontractInfo</code>.
     * @alias module:model/SubcontractingBySubcontractInfo
     */
    constructor() { 
        
        SubcontractingBySubcontractInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubcontractingBySubcontractInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubcontractingBySubcontractInfo} obj Optional instance to populate.
     * @return {module:model/SubcontractingBySubcontractInfo} The populated <code>SubcontractingBySubcontractInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubcontractingBySubcontractInfo();

            if (data.hasOwnProperty('contractorName')) {
                obj['contractorName'] = ApiClient.convertToType(data['contractorName'], 'String');
            }
            if (data.hasOwnProperty('lastUpdatedAt')) {
                obj['lastUpdatedAt'] = ApiClient.convertToType(data['lastUpdatedAt'], 'Date');
            }
            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubcontractingBySubcontractInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubcontractingBySubcontractInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['contractorName'] && !(typeof data['contractorName'] === 'string' || data['contractorName'] instanceof String)) {
            throw new Error("Expected the field `contractorName` to be a primitive type in the JSON string but got " + data['contractorName']);
        }
        // ensure the json data is a string
        if (data['itemName'] && !(typeof data['itemName'] === 'string' || data['itemName'] instanceof String)) {
            throw new Error("Expected the field `itemName` to be a primitive type in the JSON string but got " + data['itemName']);
        }

        return true;
    }


}



/**
 * @member {String} contractorName
 */
SubcontractingBySubcontractInfo.prototype['contractorName'] = undefined;

/**
 * @member {Date} lastUpdatedAt
 */
SubcontractingBySubcontractInfo.prototype['lastUpdatedAt'] = undefined;

/**
 * @member {String} itemName
 */
SubcontractingBySubcontractInfo.prototype['itemName'] = undefined;






export default SubcontractingBySubcontractInfo;

