/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubcontractingBySubcontract model module.
 * @module model/SubcontractingBySubcontract
 * @version 1.0.0
 */
class SubcontractingBySubcontract {
    /**
     * Constructs a new <code>SubcontractingBySubcontract</code>.
     * @alias module:model/SubcontractingBySubcontract
     */
    constructor() { 
        
        SubcontractingBySubcontract.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubcontractingBySubcontract</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubcontractingBySubcontract} obj Optional instance to populate.
     * @return {module:model/SubcontractingBySubcontract} The populated <code>SubcontractingBySubcontract</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubcontractingBySubcontract();

            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('jobWorkPay')) {
                obj['jobWorkPay'] = ApiClient.convertToType(data['jobWorkPay'], 'Number');
            }
            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
            if (data.hasOwnProperty('sentStock')) {
                obj['sentStock'] = ApiClient.convertToType(data['sentStock'], 'Number');
            }
            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Date');
            }
            if (data.hasOwnProperty('returnStock')) {
                obj['returnStock'] = ApiClient.convertToType(data['returnStock'], 'Number');
            }
            if (data.hasOwnProperty('returnElement')) {
                obj['returnElement'] = ApiClient.convertToType(data['returnElement'], 'Number');
            }
            if (data.hasOwnProperty('packagingType')) {
                obj['packagingType'] = ApiClient.convertToType(data['packagingType'], 'String');
            }
            if (data.hasOwnProperty('usedStock')) {
                obj['usedStock'] = ApiClient.convertToType(data['usedStock'], 'Number');
            }
            if (data.hasOwnProperty('netWeight')) {
                obj['netWeight'] = ApiClient.convertToType(data['netWeight'], 'Number');
            }
            if (data.hasOwnProperty('totalJobPay')) {
                obj['totalJobPay'] = ApiClient.convertToType(data['totalJobPay'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubcontractingBySubcontract</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubcontractingBySubcontract</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['itemName'] && !(typeof data['itemName'] === 'string' || data['itemName'] instanceof String)) {
            throw new Error("Expected the field `itemName` to be a primitive type in the JSON string but got " + data['itemName']);
        }
        // ensure the json data is a string
        if (data['packagingType'] && !(typeof data['packagingType'] === 'string' || data['packagingType'] instanceof String)) {
            throw new Error("Expected the field `packagingType` to be a primitive type in the JSON string but got " + data['packagingType']);
        }

        return true;
    }


}



/**
 * @member {Date} orderDate
 */
SubcontractingBySubcontract.prototype['orderDate'] = undefined;

/**
 * @member {Number} price
 */
SubcontractingBySubcontract.prototype['price'] = undefined;

/**
 * @member {Number} jobWorkPay
 */
SubcontractingBySubcontract.prototype['jobWorkPay'] = undefined;

/**
 * @member {String} itemName
 */
SubcontractingBySubcontract.prototype['itemName'] = undefined;

/**
 * @member {Number} sentStock
 */
SubcontractingBySubcontract.prototype['sentStock'] = undefined;

/**
 * @member {Date} returnDate
 */
SubcontractingBySubcontract.prototype['returnDate'] = undefined;

/**
 * @member {Number} returnStock
 */
SubcontractingBySubcontract.prototype['returnStock'] = undefined;

/**
 * @member {Number} returnElement
 */
SubcontractingBySubcontract.prototype['returnElement'] = undefined;

/**
 * Comma-separated packaging types
 * @member {String} packagingType
 */
SubcontractingBySubcontract.prototype['packagingType'] = undefined;

/**
 * @member {Number} usedStock
 */
SubcontractingBySubcontract.prototype['usedStock'] = undefined;

/**
 * @member {Number} netWeight
 */
SubcontractingBySubcontract.prototype['netWeight'] = undefined;

/**
 * @member {Number} totalJobPay
 */
SubcontractingBySubcontract.prototype['totalJobPay'] = undefined;

/**
 * @member {Number} totalAmount
 */
SubcontractingBySubcontract.prototype['totalAmount'] = undefined;






export default SubcontractingBySubcontract;

