/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PackagingType from './PackagingType';
import SubcontractingStatus from './SubcontractingStatus';
import Unit from './Unit';

/**
 * The SubcontractingCromeInfo model module.
 * @module model/SubcontractingCromeInfo
 * @version 1.0.0
 */
class SubcontractingCromeInfo {
    /**
     * Constructs a new <code>SubcontractingCromeInfo</code>.
     * Information about a subcontracting order for creating crome
     * @alias module:model/SubcontractingCromeInfo
     */
    constructor() { 
        
        SubcontractingCromeInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubcontractingCromeInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubcontractingCromeInfo} obj Optional instance to populate.
     * @return {module:model/SubcontractingCromeInfo} The populated <code>SubcontractingCromeInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubcontractingCromeInfo();

            if (data.hasOwnProperty('subcontractingId')) {
                obj['subcontractingId'] = ApiClient.convertToType(data['subcontractingId'], 'Number');
            }
            if (data.hasOwnProperty('contractorId')) {
                obj['contractorId'] = ApiClient.convertToType(data['contractorId'], 'Number');
            }
            if (data.hasOwnProperty('contractorName')) {
                obj['contractorName'] = ApiClient.convertToType(data['contractorName'], 'String');
            }
            if (data.hasOwnProperty('itemId')) {
                obj['itemId'] = ApiClient.convertToType(data['itemId'], 'Number');
            }
            if (data.hasOwnProperty('itemName')) {
                obj['itemName'] = ApiClient.convertToType(data['itemName'], 'String');
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('originalSentStock')) {
                obj['originalSentStock'] = ApiClient.convertToType(data['originalSentStock'], 'Number');
            }
            if (data.hasOwnProperty('returnedStock')) {
                obj['returnedStock'] = ApiClient.convertToType(data['returnedStock'], 'Number');
            }
            if (data.hasOwnProperty('returnPackagingType')) {
                obj['returnPackagingType'] = PackagingType.constructFromObject(data['returnPackagingType']);
            }
            if (data.hasOwnProperty('returnPackagingWeight')) {
                obj['returnPackagingWeight'] = ApiClient.convertToType(data['returnPackagingWeight'], 'Number');
            }
            if (data.hasOwnProperty('returnPackagingCount')) {
                obj['returnPackagingCount'] = ApiClient.convertToType(data['returnPackagingCount'], 'Number');
            }
            if (data.hasOwnProperty('netReturnedStock')) {
                obj['netReturnedStock'] = ApiClient.convertToType(data['netReturnedStock'], 'Number');
            }
            if (data.hasOwnProperty('stockAlreadyInCrome')) {
                obj['stockAlreadyInCrome'] = ApiClient.convertToType(data['stockAlreadyInCrome'], 'Number');
            }
            if (data.hasOwnProperty('availableStockForCrome')) {
                obj['availableStockForCrome'] = ApiClient.convertToType(data['availableStockForCrome'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = Unit.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('jobWorkPay')) {
                obj['jobWorkPay'] = ApiClient.convertToType(data['jobWorkPay'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SubcontractingStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubcontractingCromeInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubcontractingCromeInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['contractorName'] && !(typeof data['contractorName'] === 'string' || data['contractorName'] instanceof String)) {
            throw new Error("Expected the field `contractorName` to be a primitive type in the JSON string but got " + data['contractorName']);
        }
        // ensure the json data is a string
        if (data['itemName'] && !(typeof data['itemName'] === 'string' || data['itemName'] instanceof String)) {
            throw new Error("Expected the field `itemName` to be a primitive type in the JSON string but got " + data['itemName']);
        }

        return true;
    }


}



/**
 * @member {Number} subcontractingId
 */
SubcontractingCromeInfo.prototype['subcontractingId'] = undefined;

/**
 * @member {Number} contractorId
 */
SubcontractingCromeInfo.prototype['contractorId'] = undefined;

/**
 * @member {String} contractorName
 */
SubcontractingCromeInfo.prototype['contractorName'] = undefined;

/**
 * @member {Number} itemId
 */
SubcontractingCromeInfo.prototype['itemId'] = undefined;

/**
 * @member {String} itemName
 */
SubcontractingCromeInfo.prototype['itemName'] = undefined;

/**
 * @member {Date} orderDate
 */
SubcontractingCromeInfo.prototype['orderDate'] = undefined;

/**
 * Original stock sent to contractor
 * @member {Number} originalSentStock
 */
SubcontractingCromeInfo.prototype['originalSentStock'] = undefined;

/**
 * Stock returned by contractor (gross)
 * @member {Number} returnedStock
 */
SubcontractingCromeInfo.prototype['returnedStock'] = undefined;

/**
 * @member {module:model/PackagingType} returnPackagingType
 */
SubcontractingCromeInfo.prototype['returnPackagingType'] = undefined;

/**
 * Weight per packaging unit from return (e.g., 1.2 kg per peti)
 * @member {Number} returnPackagingWeight
 */
SubcontractingCromeInfo.prototype['returnPackagingWeight'] = undefined;

/**
 * Number of packaging units from return
 * @member {Number} returnPackagingCount
 */
SubcontractingCromeInfo.prototype['returnPackagingCount'] = undefined;

/**
 * Net returned stock after deducting packaging (returnedStock - packagingWeight * packagingCount)
 * @member {Number} netReturnedStock
 */
SubcontractingCromeInfo.prototype['netReturnedStock'] = undefined;

/**
 * Stock already allocated to existing cromes
 * @member {Number} stockAlreadyInCrome
 */
SubcontractingCromeInfo.prototype['stockAlreadyInCrome'] = undefined;

/**
 * Available stock for new crome (netReturnedStock - stockAlreadyInCrome)
 * @member {Number} availableStockForCrome
 */
SubcontractingCromeInfo.prototype['availableStockForCrome'] = undefined;

/**
 * @member {module:model/Unit} unit
 */
SubcontractingCromeInfo.prototype['unit'] = undefined;

/**
 * @member {Number} price
 */
SubcontractingCromeInfo.prototype['price'] = undefined;

/**
 * @member {Number} jobWorkPay
 */
SubcontractingCromeInfo.prototype['jobWorkPay'] = undefined;

/**
 * @member {module:model/SubcontractingStatus} status
 */
SubcontractingCromeInfo.prototype['status'] = undefined;






export default SubcontractingCromeInfo;

