/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Contractor from './Contractor';
import SubItem from './SubItem';
import SubReturn from './SubReturn';
import SubcontractingStatus from './SubcontractingStatus';
import Unit from './Unit';

/**
 * The Subcontracting model module.
 * @module model/Subcontracting
 * @version 1.0.0
 */
class Subcontracting {
    /**
     * Constructs a new <code>Subcontracting</code>.
     * @alias module:model/Subcontracting
     */
    constructor() { 
        
        Subcontracting.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Subcontracting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Subcontracting} obj Optional instance to populate.
     * @return {module:model/Subcontracting} The populated <code>Subcontracting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Subcontracting();

            if (data.hasOwnProperty('subcontractingId')) {
                obj['subcontractingId'] = ApiClient.convertToType(data['subcontractingId'], 'Number');
            }
            if (data.hasOwnProperty('contractor')) {
                obj['contractor'] = Contractor.constructFromObject(data['contractor']);
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = SubItem.constructFromObject(data['item']);
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('sentStock')) {
                obj['sentStock'] = ApiClient.convertToType(data['sentStock'], 'Number');
            }
            if (data.hasOwnProperty('jobWorkPay')) {
                obj['jobWorkPay'] = ApiClient.convertToType(data['jobWorkPay'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('subReturns')) {
                obj['subReturns'] = ApiClient.convertToType(data['subReturns'], [SubReturn]);
            }
            if (data.hasOwnProperty('totalReturnStock')) {
                obj['totalReturnStock'] = ApiClient.convertToType(data['totalReturnStock'], 'Number');
            }
            if (data.hasOwnProperty('totalNetReturnStock')) {
                obj['totalNetReturnStock'] = ApiClient.convertToType(data['totalNetReturnStock'], 'Number');
            }
            if (data.hasOwnProperty('usedStock')) {
                obj['usedStock'] = ApiClient.convertToType(data['usedStock'], 'Number');
            }
            if (data.hasOwnProperty('totalAmount')) {
                obj['totalAmount'] = ApiClient.convertToType(data['totalAmount'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = Unit.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SubcontractingStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
            if (data.hasOwnProperty('cromeCount')) {
                obj['cromeCount'] = ApiClient.convertToType(data['cromeCount'], 'Number');
            }
            if (data.hasOwnProperty('availableStockForCrome')) {
                obj['availableStockForCrome'] = ApiClient.convertToType(data['availableStockForCrome'], 'Number');
            }
            if (data.hasOwnProperty('canCreateCrome')) {
                obj['canCreateCrome'] = ApiClient.convertToType(data['canCreateCrome'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Subcontracting</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Subcontracting</code>.
     */
    static validateJSON(data) {
        // validate the optional field `contractor`
        if (data['contractor']) { // data not null
          Contractor.validateJSON(data['contractor']);
        }
        // validate the optional field `item`
        if (data['item']) { // data not null
          SubItem.validateJSON(data['item']);
        }
        if (data['subReturns']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['subReturns'])) {
                throw new Error("Expected the field `subReturns` to be an array in the JSON data but got " + data['subReturns']);
            }
            // validate the optional field `subReturns` (array)
            for (const item of data['subReturns']) {
                SubReturn.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }

        return true;
    }


}



/**
 * @member {Number} subcontractingId
 */
Subcontracting.prototype['subcontractingId'] = undefined;

/**
 * @member {module:model/Contractor} contractor
 */
Subcontracting.prototype['contractor'] = undefined;

/**
 * @member {module:model/SubItem} item
 */
Subcontracting.prototype['item'] = undefined;

/**
 * @member {Date} orderDate
 */
Subcontracting.prototype['orderDate'] = undefined;

/**
 * @member {Number} sentStock
 */
Subcontracting.prototype['sentStock'] = undefined;

/**
 * @member {Number} jobWorkPay
 */
Subcontracting.prototype['jobWorkPay'] = undefined;

/**
 * @member {Number} price
 */
Subcontracting.prototype['price'] = undefined;

/**
 * List of return entries (contractor can return stock in multiple batches)
 * @member {Array.<module:model/SubReturn>} subReturns
 */
Subcontracting.prototype['subReturns'] = undefined;

/**
 * Total gross stock returned (sum of all returns)
 * @member {Number} totalReturnStock
 */
Subcontracting.prototype['totalReturnStock'] = undefined;

/**
 * Total net stock after deducting packaging from all returns
 * @member {Number} totalNetReturnStock
 */
Subcontracting.prototype['totalNetReturnStock'] = undefined;

/**
 * @member {Number} usedStock
 */
Subcontracting.prototype['usedStock'] = undefined;

/**
 * @member {Number} totalAmount
 */
Subcontracting.prototype['totalAmount'] = undefined;

/**
 * @member {module:model/Unit} unit
 */
Subcontracting.prototype['unit'] = undefined;

/**
 * @member {module:model/SubcontractingStatus} status
 */
Subcontracting.prototype['status'] = undefined;

/**
 * @member {String} remark
 */
Subcontracting.prototype['remark'] = undefined;

/**
 * Number of crome orders created from this subcontracting
 * @member {Number} cromeCount
 */
Subcontracting.prototype['cromeCount'] = undefined;

/**
 * Available net stock for creating new cromes
 * @member {Number} availableStockForCrome
 */
Subcontracting.prototype['availableStockForCrome'] = undefined;

/**
 * Whether crome can be created (true if has return and available stock > 0)
 * @member {Boolean} canCreateCrome
 */
Subcontracting.prototype['canCreateCrome'] = undefined;






export default Subcontracting;

