/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Unit from './Unit';

/**
 * The SubOrderRequest model module.
 * @module model/SubOrderRequest
 * @version 1.0.0
 */
class SubOrderRequest {
    /**
     * Constructs a new <code>SubOrderRequest</code>.
     * @alias module:model/SubOrderRequest
     * @param contractorId {Number} 
     * @param itemId {Number} 
     * @param orderDate {Date} 
     * @param sentStock {Number} 
     * @param jobWorkPay {Number} 
     * @param price {Number} 
     * @param unit {module:model/Unit} 
     */
    constructor(contractorId, itemId, orderDate, sentStock, jobWorkPay, price, unit) { 
        
        SubOrderRequest.initialize(this, contractorId, itemId, orderDate, sentStock, jobWorkPay, price, unit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contractorId, itemId, orderDate, sentStock, jobWorkPay, price, unit) { 
        obj['contractorId'] = contractorId;
        obj['itemId'] = itemId;
        obj['orderDate'] = orderDate;
        obj['sentStock'] = sentStock;
        obj['jobWorkPay'] = jobWorkPay;
        obj['price'] = price;
        obj['unit'] = unit;
    }

    /**
     * Constructs a <code>SubOrderRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubOrderRequest} obj Optional instance to populate.
     * @return {module:model/SubOrderRequest} The populated <code>SubOrderRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubOrderRequest();

            if (data.hasOwnProperty('contractorId')) {
                obj['contractorId'] = ApiClient.convertToType(data['contractorId'], 'Number');
            }
            if (data.hasOwnProperty('itemId')) {
                obj['itemId'] = ApiClient.convertToType(data['itemId'], 'Number');
            }
            if (data.hasOwnProperty('orderDate')) {
                obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
            }
            if (data.hasOwnProperty('sentStock')) {
                obj['sentStock'] = ApiClient.convertToType(data['sentStock'], 'Number');
            }
            if (data.hasOwnProperty('jobWorkPay')) {
                obj['jobWorkPay'] = ApiClient.convertToType(data['jobWorkPay'], 'Number');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = Unit.constructFromObject(data['unit']);
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubOrderRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubOrderRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubOrderRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }

        return true;
    }


}

SubOrderRequest.RequiredProperties = ["contractorId", "itemId", "orderDate", "sentStock", "jobWorkPay", "price", "unit"];

/**
 * @member {Number} contractorId
 */
SubOrderRequest.prototype['contractorId'] = undefined;

/**
 * @member {Number} itemId
 */
SubOrderRequest.prototype['itemId'] = undefined;

/**
 * @member {Date} orderDate
 */
SubOrderRequest.prototype['orderDate'] = undefined;

/**
 * @member {Number} sentStock
 */
SubOrderRequest.prototype['sentStock'] = undefined;

/**
 * @member {Number} jobWorkPay
 */
SubOrderRequest.prototype['jobWorkPay'] = undefined;

/**
 * @member {Number} price
 */
SubOrderRequest.prototype['price'] = undefined;

/**
 * @member {module:model/Unit} unit
 */
SubOrderRequest.prototype['unit'] = undefined;

/**
 * @member {String} remark
 */
SubOrderRequest.prototype['remark'] = undefined;






export default SubOrderRequest;

