/**
 * Subcontracting Management API
 * OpenAPI for Subcontracting management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PackagingDetail from './PackagingDetail';

/**
 * The SubReturnRequest model module.
 * @module model/SubReturnRequest
 * @version 1.0.0
 */
class SubReturnRequest {
    /**
     * Constructs a new <code>SubReturnRequest</code>.
     * @alias module:model/SubReturnRequest
     * @param returnDate {Date} 
     * @param packagings {Array.<module:model/PackagingDetail>} 
     */
    constructor(returnDate, packagings) { 
        
        SubReturnRequest.initialize(this, returnDate, packagings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, returnDate, packagings) { 
        obj['returnDate'] = returnDate;
        obj['packagings'] = packagings;
    }

    /**
     * Constructs a <code>SubReturnRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubReturnRequest} obj Optional instance to populate.
     * @return {module:model/SubReturnRequest} The populated <code>SubReturnRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubReturnRequest();

            if (data.hasOwnProperty('returnDate')) {
                obj['returnDate'] = ApiClient.convertToType(data['returnDate'], 'Date');
            }
            if (data.hasOwnProperty('returnStock')) {
                obj['returnStock'] = ApiClient.convertToType(data['returnStock'], 'Number');
            }
            if (data.hasOwnProperty('packagings')) {
                obj['packagings'] = ApiClient.convertToType(data['packagings'], [PackagingDetail]);
            }
            if (data.hasOwnProperty('returnRemark')) {
                obj['returnRemark'] = ApiClient.convertToType(data['returnRemark'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubReturnRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubReturnRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubReturnRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['packagings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['packagings'])) {
                throw new Error("Expected the field `packagings` to be an array in the JSON data but got " + data['packagings']);
            }
            // validate the optional field `packagings` (array)
            for (const item of data['packagings']) {
                PackagingDetail.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['returnRemark'] && !(typeof data['returnRemark'] === 'string' || data['returnRemark'] instanceof String)) {
            throw new Error("Expected the field `returnRemark` to be a primitive type in the JSON string but got " + data['returnRemark']);
        }

        return true;
    }


}

SubReturnRequest.RequiredProperties = ["returnDate", "packagings"];

/**
 * @member {Date} returnDate
 */
SubReturnRequest.prototype['returnDate'] = undefined;

/**
 * Gross stock returned by contractor
 * @member {Number} returnStock
 */
SubReturnRequest.prototype['returnStock'] = undefined;

/**
 * @member {Array.<module:model/PackagingDetail>} packagings
 */
SubReturnRequest.prototype['packagings'] = undefined;

/**
 * @member {String} returnRemark
 */
SubReturnRequest.prototype['returnRemark'] = undefined;






export default SubReturnRequest;

